const doctorData = [
  {
    doctor_name: "Dr. Aditya Sharma",
    specialization: "Cardiologist",
    experience_years: "15",
    hospital_name: "Apollo Hospital",
    city: "Mumbai",
    avg_rating: 4.8,
    treatments: ["Angioplasty"],
  },
  {
    doctor_name: "Dr. Karan Malhotra",
    specialization: "Cardiologist",
    experience_years: "17",
    hospital_name: "Max Super Speciality",
    city: "Delhi",
    avg_rating: 4.8,
    treatments: ["Angioplasty"],
  },
  {
    doctor_name: "Dr. Priya Mehta",
    specialization: "Dermatologist",
    experience_years: "10",
    hospital_name: "Apollo Hospital",
    city: "Mumbai",
    avg_rating: 4.6,
    treatments: ["Chemical Peels"],
  },
  {
    doctor_name: "Dr. Shalini Vats",
    specialization: "Dermatologist",
    experience_years: "9",
    hospital_name: "Max Super Speciality",
    city: "Delhi",
    avg_rating: 4.7,
    treatments: ["Chemical Peels"],
  },
  {
    doctor_name: "Dr. Vikram Sethi",
    specialization: "Neurologist",
    experience_years: "18",
    hospital_name: "Apollo Hospital",
    city: "Mumbai",
    avg_rating: 4.9,
    treatments: ["Brain Tumor Surgery"],
  },
  {
    doctor_name: "Dr. Abhinav Gupta",
    specialization: "Neurologist",
    experience_years: "14",
    hospital_name: "Max Super Speciality",
    city: "Delhi",
    avg_rating: 4.9,
    treatments: ["Brain Tumor Surgery"],
  },
  {
    doctor_name: "Dr. Sneha Kapoor",
    specialization: "Orthopedic",
    experience_years: "12",
    hospital_name: "Apollo Hospital",
    city: "Mumbai",
    avg_rating: 4.7,
    treatments: ["Knee Replacement"],
  },
  {
    doctor_name: "Dr. Rahul Oberoi",
    specialization: "Orthopedic",
    experience_years: "20",
    hospital_name: "Max Super Speciality",
    city: "Delhi",
    avg_rating: 4.8,
    treatments: ["Knee Replacement"],
  },
  {
    doctor_name: "Dr. Anjali Deshmukh",
    specialization: "Gynecologist",
    experience_years: "14",
    hospital_name: "Lilavati Hospital",
    city: "Mumbai",
    avg_rating: 4.9,
    treatments: ["Laparoscopic Hysterectomy"],
  },
  {
    doctor_name: "Dr. Sonali Bose",
    specialization: "Gynecologist",
    experience_years: "15",
    hospital_name: "Manipal Hospital",
    city: "Bangalore",
    avg_rating: 4.9,
    treatments: ["Laparoscopic Hysterectomy"],
  },
  {
    doctor_name: "Dr. Rohan Varma",
    specialization: "Pediatrician",
    experience_years: "9",
    hospital_name: "Lilavati Hospital",
    city: "Mumbai",
    avg_rating: 4.7,
    treatments: ["Childhood Immunization"],
  },
  {
    doctor_name: "Dr. Naveen Kumar",
    specialization: "Pediatrician",
    experience_years: "10",
    hospital_name: "Manipal Hospital",
    city: "Bangalore",
    avg_rating: 4.7,
    treatments: ["Childhood Immunization"],
  },
  {
    doctor_name: "Dr. Sameer Gupta",
    specialization: "Gastroenterologist",
    experience_years: "20",
    hospital_name: "Lilavati Hospital",
    city: "Mumbai",
    avg_rating: 4.8,
    treatments: ["Liver Transplant"],
  },
  {
    doctor_name: "Dr. Arshad Ali",
    specialization: "Gastroenterologist",
    experience_years: "13",
    hospital_name: "Manipal Hospital",
    city: "Bangalore",
    avg_rating: 4.8,
    treatments: ["Liver Transplant"],
  },
  {
    doctor_name: "Dr. Kavita Rao",
    specialization: "Oncologist",
    experience_years: "11",
    hospital_name: "Lilavati Hospital",
    city: "Mumbai",
    avg_rating: 4.6,
    treatments: ["Radiation Therapy"],
  },
  {
    doctor_name: "Dr. Swati Iyer",
    specialization: "Oncologist",
    experience_years: "12",
    hospital_name: "Manipal Hospital",
    city: "Bangalore",
    avg_rating: 4.7,
    treatments: ["Radiation Therapy"],
  },
  {
    doctor_name: "Dr. Rajesh Khanna",
    specialization: "Psychiatrist",
    experience_years: "16",
    hospital_name: "Fortis Hospital",
    city: "Bangalore",
    avg_rating: 4.9,
    treatments: ["Cognitive Behavioral Therapy (CBT)"],
  },
  {
    doctor_name: "Dr. Deepak Nair",
    specialization: "Psychiatrist",
    experience_years: "11",
    hospital_name: "Aster CMI",
    city: "Bangalore",
    avg_rating: 4.9,
    treatments: ["Cognitive Behavioral Therapy (CBT)"],
  },
  {
    doctor_name: "Dr. Sunil Iyengar",
    specialization: "Ophthalmologist",
    experience_years: "13",
    hospital_name: "Fortis Hospital",
    city: "Bangalore",
    avg_rating: 4.8,
    treatments: ["Cataract Surgery"],
  },
  {
    doctor_name: "Dr. Lakshmi Prasad",
    specialization: "Ophthalmologist",
    experience_years: "14",
    hospital_name: "Aster CMI",
    city: "Bangalore",
    avg_rating: 4.8,
    treatments: ["Cataract Surgery"],
  },
  {
    doctor_name: "Dr. Meena Reddy",
    specialization: "Endocrinologist",
    experience_years: "10",
    hospital_name: "Fortis Hospital",
    city: "Bangalore",
    avg_rating: 4.7,
    treatments: ["Hormone Replacement Therapy"],
  },
  {
    doctor_name: "Dr. Vishal Saxena",
    specialization: "Endocrinologist",
    experience_years: "9",
    hospital_name: "Aster CMI",
    city: "Bangalore",
    avg_rating: 4.6,
    treatments: ["Hormone Replacement Therapy"],
  },
  {
    doctor_name: "Dr. Amit Taneja",
    specialization: "ENT Specialist",
    experience_years: "12",
    hospital_name: "Fortis Hospital",
    city: "Bangalore",
    avg_rating: 4.8,
    treatments: ["Cochlear Implant Surgery"],
  },
  {
    doctor_name: "Dr. Prerna Singh",
    specialization: "ENT Specialist",
    experience_years: "15",
    hospital_name: "Aster CMI",
    city: "Bangalore",
    avg_rating: 4.8,
    treatments: ["Cochlear Implant Surgery"],
  },
];

module.exports = doctorData;
