const hospitals = [
  {
    hospital_name: "Apollo Hospitals",
    address: "Sarita Vihar, Delhi Mathura Road, Delhi",
    phone: "01126925858",
    facilities: ["ICU", "MRI", "Emergency Room"],
    specializations: [
      "Cardiologist",
      "Dermatologist",
      "Neurologist",
      "Orthopedic",
    ],
    timing: { open: "08:00 AM", close: "09:00 PM" },
  },
  {
    hospital_name: "Fortis Memorial Research Institute",
    address: "Sector 44, Opposite HUDA City Centre, Gurgaon",
    phone: "01244921021",
    facilities: ["ICU", "3 Tesla MRI", "NICU"],
    specializations: [
      "Gynecologist",
      "Pediatrician",
      "Gastroenterologist",
      "Oncologist",
    ],
    timing: { open: "09:00 AM", close: "08:30 PM" },
  },
  {
    hospital_name: "Max Super Speciality Hospital",
    address: "1, 2, Press Enclave Road, Saket, Delhi",
    phone: "01126515050",
    facilities: ["ICU", "Dialysis", "Cardiac Cath Lab"],
    specializations: [
      "Psychiatrist",
      "Ophthalmologist",
      "Endocrinologist",
      "ENT Specialist",
    ],
    timing: { open: "08:00 AM", close: "08:00 PM" },
  },
  {
    hospital_name: "AIIMS",
    address: "Ansari Nagar, Delhi",
    phone: "01126588500",
    facilities: ["Emergency Care", "Advanced Labs", "Blood Bank"],
    specializations: [
      "Cardiologist",
      "Dermatologist",
      "Neurologist",
      "Orthopedic",
    ],
    timing: { open: "00:00 AM", close: "11:59 PM" },
  },
  {
    hospital_name: "Sir Ganga Ram Hospital",
    address: "Rajinder Nagar, Delhi",
    phone: "01125750000",
    facilities: ["ICU", "Organ Transplant", "Dialysis"],
    specializations: [
      "Gynecologist",
      "Pediatrician",
      "Gastroenterologist",
      "Oncologist",
    ],
    timing: { open: "08:00 AM", close: "08:00 PM" },
  },
  {
    hospital_name: "Medanta - The Medicity",
    address: "Sector 38, Gurgaon",
    phone: "01244141414",
    facilities: ["Air Ambulance", "CyberKnife", "Heart Institute"],
    specializations: [
      "Psychiatrist",
      "Ophthalmologist",
      "Endocrinologist",
      "ENT Specialist",
    ],
    timing: { open: "09:00 AM", close: "07:00 PM" },
  },
  {
    hospital_name: "Christian Medical College (CMC)",
    address: "Ida Scudder Road, Vellore",
    phone: "04162281000",
    facilities: ["Advanced Lab", "Radiology", "Pharmacy"],
    specializations: [
      "Cardiologist",
      "Dermatologist",
      "Neurologist",
      "Orthopedic",
    ],
    timing: { open: "07:30 AM", close: "06:00 PM" },
  },
  {
    hospital_name: "Apollo Hospitals",
    address: "21, Greams Lane, Chennai",
    phone: "04428293333",
    facilities: ["Proton Therapy", "Liver Transplant", "ICU"],
    specializations: [
      "Gynecologist",
      "Pediatrician",
      "Gastroenterologist",
      "Oncologist",
    ],
    timing: { open: "08:00 AM", close: "08:00 PM" },
  },
  {
    hospital_name: "Fortis Hospital",
    address: "154/9, Bannerghatta Road, Bangalore",
    phone: "08066214444",
    facilities: ["Robotic Joint Replacement", "ICU", "MRI"],
    specializations: [
      "Psychiatrist",
      "Ophthalmologist",
      "Endocrinologist",
      "ENT Specialist",
    ],
    timing: { open: "09:00 AM", close: "09:00 PM" },
  },
  {
    hospital_name: "Manipal Hospital",
    address: "98, Old Airport Road, Bangalore",
    phone: "08025024444",
    facilities: ["ICU", "Oncology Wing", "Blood Bank"],
    specializations: [
      "Cardiologist",
      "Dermatologist",
      "Neurologist",
      "Orthopedic",
    ],
    timing: { open: "08:00 AM", close: "08:00 PM" },
  },
  {
    hospital_name: "Narayana Health City",
    address: "258/A, Bommasandra, Bangalore",
    phone: "08071222222",
    facilities: ["Cardiac Cath Lab", "BMT", "NICU"],
    specializations: [
      "Gynecologist",
      "Pediatrician",
      "Gastroenterologist",
      "Oncologist",
    ],
    timing: { open: "09:00 AM", close: "08:00 PM" },
  },
  {
    hospital_name: "NIMHANS",
    address: "Hosur Road, Bangalore",
    phone: "08026995000",
    facilities: ["Neuro-imaging", "Psychiatric Emergency", "Brain Bank"],
    specializations: [
      "Psychiatrist",
      "Ophthalmologist",
      "Endocrinologist",
      "ENT Specialist",
    ],
    timing: { open: "08:00 AM", close: "04:00 PM" },
  },
  {
    hospital_name: "Kokilaben Dhirubhai Ambani Hospital",
    address: "Andheri West, Mumbai",
    phone: "02230666666",
    facilities: ["Intra-operative MRI", "Da Vinci Robot", "Sports Medicine"],
    specializations: [
      "Cardiologist",
      "Dermatologist",
      "Neurologist",
      "Orthopedic",
    ],
    timing: { open: "08:00 AM", close: "09:00 PM" },
  },
  {
    hospital_name: "MIOT International",
    address: "Mount Poonamallee Road, Chennai",
    phone: "04442002288",
    facilities: ["Keyhole Surgery", "Trauma Centre", "Bone Marrow Unit"],
    specializations: [
      "Gynecologist",
      "Pediatrician",
      "Gastroenterologist",
      "Oncologist",
    ],
    timing: { open: "09:00 AM", close: "08:00 PM" },
  },
  {
    hospital_name: "Jehangir Hospital",
    address: "32, Sassoon Road, Pune",
    phone: "02066811000",
    facilities: ["ICU", "Urology Centre", "Breast Care Clinic"],
    specializations: [
      "Psychiatrist",
      "Ophthalmologist",
      "Endocrinologist",
      "ENT Specialist",
    ],
    timing: { open: "08:00 AM", close: "08:30 PM" },
  },
  {
    hospital_name: "Ruby Hall Clinic",
    address: "40, Sassoon Road, Pune",
    phone: "02066455100",
    facilities: ["Linear Accelerator", "PET-CT", "Cardiac Lab"],
    specializations: [
      "Cardiologist",
      "Dermatologist",
      "Neurologist",
      "Orthopedic",
    ],
    timing: { open: "08:00 AM", close: "09:00 PM" },
  },
  {
    hospital_name: "Nanavati Max Super Speciality",
    address: "S.V. Road, Vile Parle, Mumbai",
    phone: "02226267500",
    facilities: ["ICU", "Liver Transplant", "MRI"],
    specializations: [
      "Gynecologist",
      "Pediatrician",
      "Gastroenterologist",
      "Oncologist",
    ],
    timing: { open: "09:00 AM", close: "08:00 PM" },
  },
  {
    hospital_name: "Sir H. N. Reliance Foundation",
    address: "Prarthana Samaj, Mumbai",
    phone: "1800221166",
    facilities: ["Smart Rooms", "Hybrid OT", "Robotic Surgery"],
    specializations: [
      "Psychiatrist",
      "Ophthalmologist",
      "Endocrinologist",
      "ENT Specialist",
    ],
    timing: { open: "08:00 AM", close: "08:00 PM" },
  },
  {
    hospital_name: "Continental Hospital",
    address: "Nanakramguda, Hyderabad",
    phone: "04467000000",
    facilities: ["ICU", "Cath Lab", "Modular OTs"],
    specializations: [
      "Cardiologist",
      "Dermatologist",
      "Neurologist",
      "Orthopedic",
    ],
    timing: { open: "08:00 AM", close: "08:00 PM" },
  },
  {
    hospital_name: "Medanta - The Medicity",
    address: "Sector 38, Gurgaon",
    phone: "01244141414",
    facilities: ["Air Ambulance", "CyberKnife", "Organ Transplant"],
    specializations: [
      "Gynecologist",
      "Pediatrician",
      "Gastroenterologist",
      "Oncologist",
    ],
    timing: { open: "09:00 AM", close: "07:00 PM" },
  },
  {
    hospital_name: "Fortis Memorial Research Institute",
    address: "Sector 44, Gurgaon",
    phone: "01244921021",
    facilities: ["ICU", "3 Tesla MRI", "Robotic Surgery"],
    specializations: [
      "Psychiatrist",
      "Ophthalmologist",
      "Endocrinologist",
      "ENT Specialist",
    ],
    timing: { open: "09:00 AM", close: "08:30 PM" },
  },
  {
    hospital_name: "Fortis Hospital",
    address: "Sector 62, Noida",
    phone: "01202400222",
    facilities: ["ICU", "Dialysis", "Cardiac Lab"],
    specializations: [
      "Cardiologist",
      "Dermatologist",
      "Neurologist",
      "Orthopedic",
    ],
    timing: { open: "08:00 AM", close: "08:00 PM" },
  },
  {
    hospital_name: "Jaypee Hospital",
    address: "Sector 128, Noida",
    phone: "01204122222",
    facilities: ["ICU", "Liver Transplant", "MRI"],
    specializations: [
      "Gynecologist",
      "Pediatrician",
      "Gastroenterologist",
      "Oncologist",
    ],
    timing: { open: "09:00 AM", close: "07:30 PM" },
  },
  {
    hospital_name: "PGIMER",
    address: "Sector 12, Chandigarh",
    phone: "01722747585",
    facilities: ["Emergency care", "Research Labs", "Organ Transplant"],
    specializations: [
      "Psychiatrist",
      "Ophthalmologist",
      "Endocrinologist",
      "ENT Specialist",
    ],
    timing: { open: "00:00 AM", close: "11:59 PM" },
  },
  {
    hospital_name: "Medanta Hospital",
    address: "Amar Shaheed Path, Lucknow",
    phone: "05224505050",
    facilities: ["ICU", "Cath Lab", "MRI"],
    specializations: [
      "Cardiologist",
      "Dermatologist",
      "Neurologist",
      "Orthopedic",
    ],
    timing: { open: "08:00 AM", close: "08:00 PM" },
  },
  {
    hospital_name: "Jeevan Rekha Hospital",
    address: "Jagatpura, Jaipur",
    phone: "01412753333",
    facilities: ["NICU", "ICU", "Modular OTs"],
    specializations: [
      "Gynecologist",
      "Pediatrician",
      "Gastroenterologist",
      "Oncologist",
    ],
    timing: { open: "08:00 AM", close: "09:00 PM" },
  },
  {
    hospital_name: "Fortis ESCORTS",
    address: "Jawaharlal Nehru Marg, Jaipur",
    phone: "01412547000",
    facilities: ["Cath Lab", "ICU", "MRI"],
    specializations: [
      "Psychiatrist",
      "Ophthalmologist",
      "Endocrinologist",
      "ENT Specialist",
    ],
    timing: { open: "09:00 AM", close: "08:00 PM" },
  },
  {
    hospital_name: "CKS Hospital",
    address: "VKI Area, Jaipur",
    phone: "01412334455",
    facilities: ["ICU", "Joint Replacement", "Emergency Room"],
    specializations: [
      "Cardiologist",
      "Dermatologist",
      "Neurologist",
      "Orthopedic",
    ],
    timing: { open: "08:00 AM", close: "08:00 PM" },
  },
  {
    hospital_name: "Apollo Hospitals",
    address: "Gandhinagar Highway, Ahmedabad",
    phone: "07966701801",
    facilities: ["ICU", "Liver Transplant", "Robotic Surgery"],
    specializations: [
      "Gynecologist",
      "Pediatrician",
      "Gastroenterologist",
      "Oncologist",
    ],
    timing: { open: "08:00 AM", close: "08:00 PM" },
  },
  {
    hospital_name: "Sterling Hospital",
    address: "Memnagar, Ahmedabad",
    phone: "07940011111",
    facilities: ["ICU", "Renal Transplant", "Dialysis"],
    specializations: [
      "Psychiatrist",
      "Ophthalmologist",
      "Endocrinologist",
      "ENT Specialist",
    ],
    timing: { open: "09:00 AM", close: "08:30 PM" },
  },
];

module.exports = hospitals;
