const hospitals = [
  
  {
    hospital_name: "Apollo Hospitals",
    hospital_type: "Private",
    description: "A premier multi-specialty healthcare provider known for clinical excellence and advanced robotic surgeries.",
    location: {
      address: "Sarita Vihar, Delhi Mathura Road",
      city: "Delhi",
      state: "Delhi",
    },
    contact: { phone: "01126925858", email: "infodelhi@apollohospitals.com" },
    facilities: [
      "ICU",
      "MRI",
      "CT Scan",
      "Pathology Lab",
      "Pharmacy",
      "Robotic Surgery",
      "Emergency Room",
    ],
    specializations: [
      "Cardiologist",
      "Dermatologist",
      "Neurologist",
      "Orthopedic",
    ],
    services: {
      emergency_24x7: true,
      ambulance_service: true,
      online_appointment: true,
      blood_bank_available: true,
      insurance_accepted: [
        "Star Health",
        "HDFC ERGO",
        "ICICI Lombard",
        "Care Health",
      ],
    },
    timing: { opening_time: "08:00 AM", closing_time: "09:00 PM" },
  },
  {
    hospital_name: "Fortis Memorial Research Institute",
    hospital_type: "Private",
    description: "A quaternary care hospital with a focus on high-end technology and international patient care.",
    location: {
      address: "Sector 44, Opposite HUDA City Centre",
      city: "Gurgaon",
      state: "Haryana",
    },
    contact: { phone: "01244921021", email: "enquiry@fortishealthcare.com" },
    facilities: [
      "ICU",
      "3 Tesla MRI",
      "256 Slice CT",
      "Bone Marrow Transplant Unit",
      "NICU",
    ],
    specializations: [
      "Gynecologist",
      "Pediatrician",
      "Gastroenterologist",
      "Oncologist",
    ],
    services: {
      emergency_24x7: true,
      ambulance_service: true,
      online_appointment: true,
      blood_bank_available: true,
      insurance_accepted: ["Niva Bupa", "Bajaj Allianz", "Star Health"],
    },
    timing: { opening_time: "09:00 AM", closing_time: "08:30 PM" },
  },
  {
    hospital_name: "Max Super Speciality Hospital",
    hospital_type: "Private",
    description: "Leading healthcare facility in South Delhi specializing in cardiac and neurosciences.",
    location: {
      address: "1, 2, Press Enclave Road, Saket",
      city: "Delhi",
      state: "Delhi",
    },
    contact: { phone: "01126515050", email: "info@maxhealthcare.com" },
    facilities: [
      "ICU",
      "Dialysis",
      "Cardiac Cath Lab",
      "PET-CT Scan",
      "Endoscopy Suite",
    ],
    specializations: [
      "Psychiatrist",
      "Ophthalmologist",
      "Endocrinologist",
      "ENT Specialist",
    ],
    services: {
      emergency_24x7: true,
      ambulance_service: true,
      online_appointment: true,
      blood_bank_available: true,
      insurance_accepted: ["Aditya Birla", "Max Bupa", "HDFC ERGO"],
    },
    timing: { opening_time: "08:00 AM", closing_time: "08:00 PM" },
  },
  {
    hospital_name: "AIIMS (All India Institute of Medical Sciences)",
    hospital_type: "Government",
    description: "India's premier public medical research university and hospital providing highly subsidized care.",
    location: {
      address: "Ansari Nagar",
      city: "Delhi",
      state: "Delhi",
    },
    contact: { phone: "01126588500", email: "director@aiims.edu" },
    facilities: [
      "Emergency Care",
      "Advanced Labs",
      "Research Center",
      "Generic Pharmacy",
      "Blood Bank",
    ],
    specializations: [
      "Cardiologist",
      "Dermatologist",
      "Neurologist",
      "Orthopedic",
    ],
    services: {
      emergency_24x7: true,
      ambulance_service: true,
      online_appointment: true,
      blood_bank_available: true,
      insurance_accepted: ["CGHS", "ECHS", "PM-JAY (Ayushman Bharat)"],
    },
    timing: { opening_time: "00:00 AM", closing_time: "11:59 PM" },
  },
  {
    hospital_name: "Sir Ganga Ram Hospital",
    hospital_type: "Private",
    description: "A multi-speciality state-of-the-art hospital known for its charitable trust and high quality of care.",
    location: {
      address: "Rajinder Nagar",
      city: "Delhi",
      state: "Delhi",
    },
    contact: { phone: "01125750000", email: "gangaram@sgrh.com" },
    facilities: [
      "ICU",
      "Organ Transplant Unit",
      "Dialysis",
      "Laboratory",
      "Cafeteria",
    ],
    specializations: [
      "Gynecologist",
      "Pediatrician",
      "Gastroenterologist",
      "Oncologist",
    ],
    services: {
      emergency_24x7: true,
      ambulance_service: true,
      online_appointment: true,
      blood_bank_available: true,
      insurance_accepted: ["Star Health", "United India", "Oriental Insurance"],
    },
    timing: { opening_time: "08:00 AM", closing_time: "08:00 PM" },
  },
  {
    hospital_name: "Medanta - The Medicity",
    hospital_type: "Private",
    description: "Founded by Dr. Naresh Trehan, this hospital is a global destination for cardiac care.",
    location: {
      address: "CH Baktawar Singh Road, Sector 38",
      city: "Gurgaon",
      state: "Haryana",
    },
    contact: { phone: "01244141414", email: "info@medanta.org" },
    facilities: [
      "Air Ambulance",
      "CyberKnife",
      "Heart Institute",
      "Linear Accelerator",
      "Robot Surgery",
    ],
    specializations: [
      "Psychiatrist",
      "Ophthalmologist",
      "Endocrinologist",
      "ENT Specialist",
    ],
    services: {
      emergency_24x7: true,
      ambulance_service: true,
      online_appointment: true,
      blood_bank_available: true,
      insurance_accepted: ["HDFC ERGO", "Reliance General", "TATA AIG"],
    },
    timing: { opening_time: "09:00 AM", closing_time: "07:00 PM" },
  },
  {
    hospital_name: "Christian Medical College (CMC)",
    hospital_type: "Trust",
    description: "Ranked among the best in India, specializing in low-cost, high-tech healthcare and education.",
    location: {
      address: "Ida Scudder Road",
      city: "Vellore",
      state: "Tamil Nadu",
    },
    contact: { phone: "04162281000", email: "directorate@cmcvellore.ac.in" },
    facilities: ["Hostels", "Advanced Lab", "Radiology", "Library", "Pharmacy"],
    specializations: [
      "Cardiologist",
      "Dermatologist",
      "Neurologist",
      "Orthopedic",
    ],
    services: {
      emergency_24x7: true,
      ambulance_service: true,
      online_appointment: true,
      blood_bank_available: true,
      insurance_accepted: ["Star Health", "Government Schemes", "Self-Pay"],
    },
    timing: { opening_time: "07:30 AM", closing_time: "06:00 PM" },
  },
  {
    hospital_name: "Apollo Hospitals",
    hospital_type: "Private",
    description: "The main branch in Chennai, pioneering organ transplants and cardiac bypass in South India.",
    location: {
      address: "21, Greams Lane, Off Greams Road",
      city: "Chennai",
      state: "Tamil Nadu",
    },
    contact: { phone: "04428293333", email: "greams_road@apollohospitals.com" },
    facilities: [
      "Proton Therapy",
      "Liver Transplant Centre",
      "Cardiac Lab",
      "MRI",
      "ICU",
    ],
    specializations: [
      "Gynecologist",
      "Pediatrician",
      "Gastroenterologist",
      "Oncologist",
    ],
    services: {
      emergency_24x7: true,
      ambulance_service: true,
      online_appointment: true,
      blood_bank_available: true,
      insurance_accepted: ["Star Health", "ICICI Lombard", "Cholamandalam"],
    },
    timing: { opening_time: "08:00 AM", closing_time: "08:00 PM" },
  },
  {
    hospital_name: "Fortis Hospital",
    hospital_type: "Private",
    description: "Specialized care facility known for orthopedic and multi-organ transplant procedures.",
    location: {
      address: "154/9, Bannerghatta Road",
      city: "Bangalore",
      state: "Karnataka",
    },
    contact: {
      phone: "08066214444",
      email: "enquiry.bgroad@fortishealthcare.com",
    },
    facilities: [
      "Robotic Joint Replacement",
      "ICU",
      "Physiotherapy",
      "Pharmacy",
      "MRI",
    ],
    specializations: [
      "Psychiatrist",
      "Ophthalmologist",
      "Endocrinologist",
      "ENT Specialist",
    ],
    services: {
      emergency_24x7: true,
      ambulance_service: true,
      online_appointment: true,
      blood_bank_available: true,
      insurance_accepted: ["Niva Bupa", "HDFC ERGO", "Star Health"],
    },
    timing: { opening_time: "09:00 AM", closing_time: "09:00 PM" },
  },
  {
    hospital_name: "Manipal Hospital",
    hospital_type: "Private",
    description: "Flagship hospital of the Manipal Group, known for quaternary care and ethical practices.",
    location: {
      address: "98, Old Airport Road",
      city: "Bangalore",
      state: "Karnataka",
    },
    contact: { phone: "08025024444", email: "info@manipalhospitals.com" },
    facilities: [
      "ICU",
      "Dialysis",
      "Oncology Wing",
      "Cardiac Lab",
      "Blood Bank",
    ],
    specializations: [
      "Cardiologist",
      "Dermatologist",
      "Neurologist",
      "Orthopedic",
    ],
    services: {
      emergency_24x7: true,
      ambulance_service: true,
      online_appointment: true,
      blood_bank_available: true,
      insurance_accepted: ["Care Health", "Star Health", "ICICI Lombard"],
    },
    timing: { opening_time: "08:00 AM", closing_time: "08:00 PM" },
  },

  
  {
    hospital_name: "Narayana Health City",
    hospital_type: "Private",
    description: "One of the world's largest cardiac centers, founded by Dr. Devi Shetty, focusing on affordable healthcare.",
    location: {
      address: "258/A, Bommasandra Industrial Area",
      city: "Bangalore",
      state: "Karnataka",
    },
    contact: { phone: "08071222222", email: "info@narayanahealth.org" },
    facilities: [
      "ICU",
      "Cardiac Cath Lab",
      "Bone Marrow Transplant",
      "MRI",
      "Largest NICU in Asia",
    ],
    specializations: [
      "Gynecologist",
      "Pediatrician",
      "Gastroenterologist",
      "Oncologist",
    ],
    services: {
      emergency_24x7: true,
      ambulance_service: true,
      online_appointment: true,
      blood_bank_available: true,
      insurance_accepted: ["Star Health", "HDFC ERGO", "Ayushman Bharat"],
    },
    timing: { opening_time: "09:00 AM", closing_time: "08:00 PM" },
  },
  {
    hospital_name: "NIMHANS",
    hospital_type: "Government",
    description: "The apex center for mental health and neuroscience education in India.",
    location: {
      address: "Hosur Road",
      city: "Bangalore",
      state: "Karnataka",
    },
    contact: { phone: "08026995000", email: "director@nimhans.ac.in" },
    facilities: [
      "Advanced Neuro-imaging",
      "Psychiatric Emergency",
      "Brain Bank",
      "Neuropathology Lab",
    ],
    specializations: [
      "Psychiatrist",
      "Ophthalmologist",
      "Endocrinologist",
      "ENT Specialist",
    ],
    services: {
      emergency_24x7: true,
      ambulance_service: true,
      online_appointment: true,
      blood_bank_available: false,
      insurance_accepted: ["CGHS", "ECHS", "PM-JAY"],
    },
    timing: { opening_time: "08:00 AM", closing_time: "04:00 PM" },
  },
  {
    hospital_name: "Kokilaben Dhirubhai Ambani Hospital",
    hospital_type: "Private",
    description: "A social initiative by Reliance Group, providing world-class healthcare technology in Mumbai.",
    location: {
      address: "Rao Saheb, Achutrao Patwardhan Marg, Andheri West",
      city: "Mumbai",
      state: "Maharashtra",
    },
    contact: { phone: "02230666666", email: "info@kokilabenhospital.com" },
    facilities: [
      "Intra-operative MRI",
      "Da Vinci Robot",
      "Full-time Specialist System",
      "Sports Medicine Centre",
    ],
    specializations: [
      "Cardiologist",
      "Dermatologist",
      "Neurologist",
      "Orthopedic",
    ],
    services: {
      emergency_24x7: true,
      ambulance_service: true,
      online_appointment: true,
      blood_bank_available: true,
      insurance_accepted: ["Reliance General", "Star Health", "ICICI Lombard"],
    },
    timing: { opening_time: "08:00 AM", closing_time: "09:00 PM" },
  },
  {
    hospital_name: "MIOT International",
    hospital_type: "Private",
    description: "Known for its expertise in Orthopaedics, MIOT is now a multi-specialty leader in Chennai.",
    location: {
      address: "4/112, Mount Poonamallee Road",
      city: "Chennai",
      state: "Tamil Nadu",
    },
    contact: { phone: "04442002288", email: "enquiry@miotinternational.com" },
    facilities: [
      "Keyhole Surgery",
      "Level 1 Trauma Centre",
      "Bone Marrow Unit",
      "Pathology Lab",
    ],
    specializations: [
      "Gynecologist",
      "Pediatrician",
      "Gastroenterologist",
      "Oncologist",
    ],
    services: {
      emergency_24x7: true,
      ambulance_service: true,
      online_appointment: true,
      blood_bank_available: true,
      insurance_accepted: ["Max Bupa", "Star Health", "Oriental Insurance"],
    },
    timing: { opening_time: "09:00 AM", closing_time: "08:00 PM" },
  },
  {
    hospital_name: "Jehangir Hospital",
    hospital_type: "Private",
    description: "A heritage hospital in Pune with a legacy of providing quality care and trust.",
    location: {
      address: "32, Sassoon Road",
      city: "Pune",
      state: "Maharashtra",
    },
    contact: { phone: "02066811000", email: "info@jehangirhospital.com" },
    facilities: [
      "ICU",
      "Urology Centre",
      "Breast Care Clinic",
      "Dialysis",
      "CT Scan",
    ],
    specializations: [
      "Psychiatrist",
      "Ophthalmologist",
      "Endocrinologist",
      "ENT Specialist",
    ],
    services: {
      emergency_24x7: true,
      ambulance_service: true,
      online_appointment: true,
      blood_bank_available: true,
      insurance_accepted: ["Star Health", "HDFC ERGO", "New India Assurance"],
    },
    timing: { opening_time: "08:00 AM", closing_time: "08:30 PM" },
  },
  {
    hospital_name: "Ruby Hall Clinic",
    hospital_type: "Private",
    description: "A major multi-specialty hospital in Pune, pioneer in organ transplants and cancer care.",
    location: {
      address: "40, Sassoon Road",
      city: "Pune",
      state: "Maharashtra",
    },
    contact: { phone: "02066455100", email: "info@rubyhall.com" },
    facilities: [
      "ICU",
      "Linear Accelerator",
      "PET-CT",
      "Cardiac Lab",
      "Blood Bank",
    ],
    specializations: [
      "Cardiologist",
      "Dermatologist",
      "Neurologist",
      "Orthopedic",
    ],
    services: {
      emergency_24x7: true,
      ambulance_service: true,
      online_appointment: true,
      blood_bank_available: true,
      insurance_accepted: ["ICICI Lombard", "Bajaj Allianz", "Star Health"],
    },
    timing: { opening_time: "08:00 AM", closing_time: "09:00 PM" },
  },
  {
    hospital_name: "Nanavati Max Super Speciality",
    hospital_type: "Private",
    description: "One of Mumbai’s oldest and most iconic hospitals, now part of the Max Healthcare network.",
    location: {
      address: "S.V. Road, Vile Parle (West)",
      city: "Mumbai",
      state: "Maharashtra",
    },
    contact: { phone: "02226267500", email: "info@nanavatihospital.org" },
    facilities: [
      "ICU",
      "Liver Transplant Centre",
      "Advanced Oncology",
      "MRI",
      "Pathology",
    ],
    specializations: [
      "Gynecologist",
      "Pediatrician",
      "Gastroenterologist",
      "Oncologist",
    ],
    services: {
      emergency_24x7: true,
      ambulance_service: true,
      online_appointment: true,
      blood_bank_available: true,
      insurance_accepted: ["Max Bupa", "HDFC ERGO", "Aditya Birla"],
    },
    timing: { opening_time: "09:00 AM", closing_time: "08:00 PM" },
  },
  {
    hospital_name: "Sir H. N. Reliance Foundation Hospital",
    hospital_type: "Private",
    description: "A state-of-the-art quaternary care hospital known for luxury care and cutting-edge tech.",
    location: {
      address: "Raja Rammohan Roy Road, Prarthana Samaj",
      city: "Mumbai",
      state: "Maharashtra",
    },
    contact: { phone: "1800221166", email: "info@rfhospital.org" },
    facilities: [
      "Smart Hospital Rooms",
      "Hybrid OT",
      "Robotic Surgery",
      "ICU",
      "Blood Bank",
    ],
    specializations: [
      "Psychiatrist",
      "Ophthalmologist",
      "Endocrinologist",
      "ENT Specialist",
    ],
    services: {
      emergency_24x7: true,
      ambulance_service: true,
      online_appointment: true,
      blood_bank_available: true,
      insurance_accepted: ["Reliance General", "Star Health", "TATA AIG"],
    },
    timing: { opening_time: "08:00 AM", closing_time: "08:00 PM" },
  },
  {
    hospital_name: "Continental Hospital",
    hospital_type: "Private",
    description: "A JCI accredited hospital in Hyderabad providing integrated multi-specialty care.",
    location: {
      address: "Financial District, Nanakramguda",
      city: "Hyderabad",
      state: "Telangana",
    },
    contact: { phone: "04467000000", email: "info@continentalhospitals.com" },
    facilities: [
      "ICU",
      "Cath Lab",
      "Modular OTs",
      "MRI",
      "Comprehensive Rehab",
    ],
    specializations: [
      "Cardiologist",
      "Dermatologist",
      "Neurologist",
      "Orthopedic",
    ],
    services: {
      emergency_24x7: true,
      ambulance_service: true,
      online_appointment: true,
      blood_bank_available: true,
      insurance_accepted: ["Care Health", "Star Health", "HDFC ERGO"],
    },
    timing: { opening_time: "08:00 AM", closing_time: "08:00 PM" },
  },
  {
    hospital_name: "Medanta - The Medicity",
    hospital_type: "Private",
    description: "The main campus of Medanta, a global leader in complex cardiac and liver transplants.",
    location: {
      address: "Sector 38",
      city: "Gurgaon",
      state: "Haryana",
    },
    contact: { phone: "01244141414", email: "info@medanta.org" },
    facilities: [
      "Air Ambulance",
      "CyberKnife",
      "Organ Transplant Unit",
      "Pathology",
      "ICU",
    ],
    specializations: [
      "Gynecologist",
      "Pediatrician",
      "Gastroenterologist",
      "Oncologist",
    ],
    services: {
      emergency_24x7: true,
      ambulance_service: true,
      online_appointment: true,
      blood_bank_available: true,
      insurance_accepted: ["Star Health", "Niva Bupa", "TATA AIG"],
    },
    timing: { opening_time: "09:00 AM", closing_time: "07:00 PM" },
  },

  {
    hospital_name: "Fortis Memorial Research Institute",
    hospital_type: "Private",
    description: "A flagship hospital of Fortis, known for its focus on robotic surgeries and neurosciences.",
    location: {
      address: "Sector 44, Opposite HUDA City Centre",
      city: "Gurgaon",
      state: "Haryana",
    },
    contact: { phone: "01244921021", email: "care.fmri@fortishealthcare.com" },
    facilities: [
      "ICU",
      "3 Tesla MRI",
      "Robotic Surgery",
      "Bone Marrow Transplant",
      "Radiology",
    ],
    specializations: [
      "Psychiatrist",
      "Ophthalmologist",
      "Endocrinologist",
      "ENT Specialist",
    ],
    services: {
      emergency_24x7: true,
      ambulance_service: true,
      online_appointment: true,
      blood_bank_available: true,
      insurance_accepted: ["Niva Bupa", "Star Health", "HDFC ERGO"],
    },
    timing: { opening_time: "09:00 AM", closing_time: "08:30 PM" },
  },
  {
    hospital_name: "Fortis Hospital",
    hospital_type: "Private",
    description: "Leading multi-specialty hospital in Noida with a focus on cardiac and orthopedic care.",
    location: {
      address: "B-22, Sector 62",
      city: "Noida",
      state: "Uttar Pradesh",
    },
    contact: {
      phone: "01202400222",
      email: "contact.noida@fortishealthcare.com",
    },
    facilities: ["ICU", "Dialysis", "Cardiac Lab", "CT Scan", "Emergency 24x7"],
    specializations: [
      "Cardiologist",
      "Dermatologist",
      "Neurologist",
      "Orthopedic",
    ],
    services: {
      emergency_24x7: true,
      ambulance_service: true,
      online_appointment: true,
      blood_bank_available: true,
      insurance_accepted: ["Bajaj Allianz", "Star Health", "Care Health"],
    },
    timing: { opening_time: "08:00 AM", closing_time: "08:00 PM" },
  },
  {
    hospital_name: "Jaypee Hospital",
    hospital_type: "Private",
    description: "A large-scale multi-specialty facility designed to provide tertiary care in a patient-friendly environment.",
    location: {
      address: "Sector 128",
      city: "Noida",
      state: "Uttar Pradesh",
    },
    contact: { phone: "01204122222", email: "info@jaypeehospital.com" },
    facilities: [
      "ICU",
      "Advanced Oncology",
      "Liver Transplant",
      "MRI",
      "Pathology",
    ],
    specializations: [
      "Gynecologist",
      "Pediatrician",
      "Gastroenterologist",
      "Oncologist",
    ],
    services: {
      emergency_24x7: true,
      ambulance_service: true,
      online_appointment: true,
      blood_bank_available: true,
      insurance_accepted: ["TATA AIG", "HDFC ERGO", "Star Health"],
    },
    timing: { opening_time: "09:00 AM", closing_time: "07:30 PM" },
  },
  {
    hospital_name: "PGIMER",
    hospital_type: "Government",
    description: "A prestigious medical and research institution providing advanced healthcare to North India.",
    location: {
      address: "Sector 12",
      city: "Chandigarh",
      state: "Chandigarh",
    },
    contact: { phone: "01722747585", email: "pgimer-chd@nic.in" },
    facilities: [
      "Emergency care",
      "Research Labs",
      "Organ Transplant",
      "Specialized Clinics",
    ],
    specializations: [
      "Psychiatrist",
      "Ophthalmologist",
      "Endocrinologist",
      "ENT Specialist",
    ],
    services: {
      emergency_24x7: true,
      ambulance_service: true,
      online_appointment: true,
      blood_bank_available: true,
      insurance_accepted: ["CGHS", "ECHS", "PM-JAY"],
    },
    timing: { opening_time: "00:00 AM", closing_time: "11:59 PM" },
  },
  {
    hospital_name: "Medanta Hospital",
    hospital_type: "Private",
    description: "Bringing world-class cardiac and multi-specialty care to the heart of Uttar Pradesh.",
    location: {
      address: "Sector 7, Amar Shaheed Path",
      city: "Lucknow",
      state: "Uttar Pradesh",
    },
    contact: { phone: "05224505050", email: "info.lucknow@medanta.org" },
    facilities: ["ICU", "Cath Lab", "MRI", "Dialysis", "Pathology"],
    specializations: [
      "Cardiologist",
      "Dermatologist",
      "Neurologist",
      "Orthopedic",
    ],
    services: {
      emergency_24x7: true,
      ambulance_service: true,
      online_appointment: true,
      blood_bank_available: true,
      insurance_accepted: ["Star Health", "HDFC ERGO", "Niva Bupa"],
    },
    timing: { opening_time: "08:00 AM", closing_time: "08:00 PM" },
  },
  {
    hospital_name: "Jeevan Rekha Hospital",
    hospital_type: "Private",
    description: "A leading healthcare provider in Jaipur, focusing on critical care and mother & child health.",
    location: {
      address: "Jagatpura",
      city: "Jaipur",
      state: "Rajasthan",
    },
    contact: { phone: "01412753333", email: "info@jeevanrekha.com" },
    facilities: ["NICU", "ICU", "Modular OTs", "Blood Bank", "Diagnostics"],
    specializations: [
      "Gynecologist",
      "Pediatrician",
      "Gastroenterologist",
      "Oncologist",
    ],
    services: {
      emergency_24x7: true,
      ambulance_service: true,
      online_appointment: true,
      blood_bank_available: true,
      insurance_accepted: ["Star Health", "Reliance", "United India"],
    },
    timing: { opening_time: "08:00 AM", closing_time: "09:00 PM" },
  },
  {
    hospital_name: "Fortis ESCORTS",
    hospital_type: "Private",
    description: "Specialized cardiac care hospital known for non-invasive cardiology and emergency heart care.",
    location: {
      address: "Jawaharlal Nehru Marg",
      city: "Jaipur",
      state: "Rajasthan",
    },
    contact: {
      phone: "01412547000",
      email: "contact.jaipur@fortishealthcare.com",
    },
    facilities: ["Cath Lab", "ICU", "Endocrinology Lab", "ENT Unit", "MRI"],
    specializations: [
      "Psychiatrist",
      "Ophthalmologist",
      "Endocrinologist",
      "ENT Specialist",
    ],
    services: {
      emergency_24x7: true,
      ambulance_service: true,
      online_appointment: true,
      blood_bank_available: true,
      insurance_accepted: ["HDFC ERGO", "Max Bupa", "Star Health"],
    },
    timing: { opening_time: "09:00 AM", closing_time: "08:00 PM" },
  },
  {
    hospital_name: "CKS Hospital",
    hospital_type: "Private",
    description: "Comprehensive multi-specialty hospital providing affordable healthcare in Rajasthan.",
    location: {
      address: "Vishwakarma Industrial Area",
      city: "Jaipur",
      state: "Rajasthan",
    },
    contact: { phone: "01412334455", email: "info@ckshospital.com" },
    facilities: [
      "ICU",
      "Neuro Labs",
      "Joint Replacement",
      "Emergency Room",
      "Pharmacy",
    ],
    specializations: [
      "Cardiologist",
      "Dermatologist",
      "Neurologist",
      "Orthopedic",
    ],
    services: {
      emergency_24x7: true,
      ambulance_service: true,
      online_appointment: true,
      blood_bank_available: true,
      insurance_accepted: [
        "Star Health",
        "ICICI Lombard",
        "Government Schemes",
      ],
    },
    timing: { opening_time: "08:00 AM", closing_time: "08:00 PM" },
  },
  {
    hospital_name: "Apollo Hospitals",
    hospital_type: "Private",
    description: "Gujarat's leading multi-specialty hospital known for high success rates in transplants.",
    location: {
      address: "Gandhinagar-Ahmedabad Highway",
      city: "Ahmedabad",
      state: "Gujarat",
    },
    contact: { phone: "07966701801", email: "ahmedabad@apollohospitals.com" },
    facilities: [
      "ICU",
      "Liver Transplant Centre",
      "Robotic Surgery",
      "MRI",
      "Pathology",
    ],
    specializations: [
      "Gynecologist",
      "Pediatrician",
      "Gastroenterologist",
      "Oncologist",
    ],
    services: {
      emergency_24x7: true,
      ambulance_service: true,
      online_appointment: true,
      blood_bank_available: true,
      insurance_accepted: ["Star Health", "HDFC ERGO", "Bajaj Allianz"],
    },
    timing: { opening_time: "08:00 AM", closing_time: "08:00 PM" },
  },
  {
    hospital_name: "Sterling Hospital",
    hospital_type: "Private",
    description: "A major player in Gujarat’s healthcare landscape, specialized in critical care and endocrinology.",
    location: {
      address: "Sterling Hospital Road, Memnagar",
      city: "Ahmedabad",
      state: "Gujarat",
    },
    contact: { phone: "07940011111", email: "info@sterlinghospitals.com" },
    facilities: [
      "ICU",
      "Renal Transplant Unit",
      "Dialysis",
      "CT Scan",
      "ENT Unit",
    ],
    specializations: [
      "Psychiatrist",
      "Ophthalmologist",
      "Endocrinologist",
      "ENT Specialist",
    ],
    services: {
      emergency_24x7: true,
      ambulance_service: true,
      online_appointment: true,
      blood_bank_available: true,
      insurance_accepted: ["Care Health", "Star Health", "ICICI Lombard"],
    },
    timing: { opening_time: "09:00 AM", closing_time: "08:30 PM" },
  }
];

module.exports = hospitals;
