const doctors = [
  // ================= CARDIOLOGISTS =================
  {
    doctor_id: "D01",
    doctor_name: "Dr. Aditya Sharma",
    image: "/uploads/doctors/d1.jpeg",
    specialization: "Cardiologist",
    treatment: "Angioplasty",
    experience_years: 15,
    hospital: {
      hospital_id: "H001",
      hospital_name: "Apollo Hospital",
      city: "Mumbai",
      state: "Maharashtra",
    },
    consultation_fee: 1200,
    consultation_mode: "both",
    avg_rating: 4.8,
    total_reviews: 1250,
    patients_treated: 5000,
    verified: true,
  },
  {
    doctor_id: "D13",
    doctor_name: "Dr. Karan Malhotra",
    image: "/uploads/doctors/d13.jpeg",
    specialization: "Cardiologist",
    treatment: "Heart Bypass Surgery (CABG)",
    experience_years: 17,
    hospital: {
      hospital_id: "H004",
      hospital_name: "Max Super Speciality",
      city: "Delhi",
      state: "Delhi",
    },
    consultation_fee: 1500,
    consultation_mode: "offline",
    avg_rating: 4.8,
    total_reviews: 2100,
    patients_treated: 9500,
    verified: true,
  },
  {
    doctor_id: "D25",
    doctor_name: "Dr. Manish Hegde",
    image: "/uploads/doctors/d25.jpeg",
    specialization: "Cardiologist",
    treatment: "Heart Valve Repair",
    experience_years: 19,
    hospital: {
      hospital_id: "H007",
      hospital_name: "Apollo Health City",
      city: "Hyderabad",
      state: "Telangana",
    },
    consultation_fee: 1300,
    consultation_mode: "offline",
    avg_rating: 4.9,
    total_reviews: 3100,
    patients_treated: 12500,
    verified: true,
  },

  // ================= NEUROLOGISTS =================
  {
    doctor_id: "D03",
    doctor_name: "Dr. Vikram Sethi",
    image: "/uploads/doctors/d3.jpeg",
    specialization: "Neurologist",
    treatment: "Brain Tumor Surgery",
    experience_years: 18,
    hospital: {
      hospital_id: "H001",
      hospital_name: "Apollo Hospital",
      city: "Mumbai",
      state: "Maharashtra",
    },
    consultation_fee: 1500,
    consultation_mode: "offline",
    avg_rating: 4.9,
    total_reviews: 2100,
    patients_treated: 7500,
    verified: true,
  },
  {
    doctor_id: "D15",
    doctor_name: "Dr. Abhinav Gupta",
    image: "/uploads/doctors/d15.jpeg",
    specialization: "Neurologist",
    treatment: "Spinal Fusion Surgery",
    experience_years: 14,
    hospital: {
      hospital_id: "H004",
      hospital_name: "Max Super Speciality",
      city: "Delhi",
      state: "Delhi",
    },
    consultation_fee: 1300,
    consultation_mode: "offline",
    avg_rating: 4.9,
    total_reviews: 840,
    patients_treated: 5200,
    verified: true,
  },

  // ================= ORTHOPEDICS =================
  {
    doctor_id: "D04",
    doctor_name: "Dr. Sneha Kapoor",
    image: "/uploads/doctors/d4.jpeg",
    specialization: "Orthopedic",
    treatment: "Knee Replacement",
    experience_years: 12,
    hospital: {
      hospital_id: "H001",
      hospital_name: "Apollo Hospital",
      city: "Mumbai",
      state: "Maharashtra",
    },
    consultation_fee: 1000,
    consultation_mode: "both",
    avg_rating: 4.7,
    total_reviews: 1400,
    patients_treated: 4200,
    verified: true,
  },
  {
    doctor_id: "D16",
    doctor_name: "Dr. Rahul Oberoi",
    image: "/uploads/doctors/d16.jpeg",
    specialization: "Orthopedic",
    treatment: "Hip Replacement",
    experience_years: 20,
    hospital: {
      hospital_id: "H004",
      hospital_name: "Max Super Speciality",
      city: "Delhi",
      state: "Delhi",
    },
    consultation_fee: 1200,
    consultation_mode: "both",
    avg_rating: 4.8,
    total_reviews: 2900,
    patients_treated: 11000,
    verified: true,
  },

  // ================= OPHTHALMOLOGISTS =================
  {
    doctor_id: "D10",
    doctor_name: "Dr. Sunil Iyengar",
    image: "/uploads/doctors/d10.jpeg",
    specialization: "Ophthalmologist",
    treatment: "Cataract Surgery",
    experience_years: 13,
    hospital: {
      hospital_id: "H003",
      hospital_name: "Fortis Hospital",
      city: "Bangalore",
      state: "Karnataka",
    },
    consultation_fee: 600,
    consultation_mode: "offline",
    avg_rating: 4.8,
    total_reviews: 1500,
    patients_treated: 9000,
    verified: true,
  },
  {
    doctor_id: "D22",
    doctor_name: "Dr. Lakshmi Prasad",
    image: "/uploads/doctors/d22.jpeg",
    specialization: "Ophthalmologist",
    treatment: "LASIK Eye Surgery",
    experience_years: 14,
    hospital: {
      hospital_id: "H006",
      hospital_name: "Aster CMI",
      city: "Bangalore",
      state: "Karnataka",
    },
    consultation_fee: 700,
    consultation_mode: "offline",
    avg_rating: 4.8,
    total_reviews: 1300,
    patients_treated: 7200,
    verified: true,
  },

  // ================= ONCOLOGISTS =================
  {
    doctor_id: "D08",
    doctor_name: "Dr. Kavita Rao",
    image: "/uploads/doctors/d8.jpeg",
    specialization: "Oncologist",
    treatment: "Chemotherapy (Per Cycle)",
    experience_years: 11,
    hospital: {
      hospital_id: "H002",
      hospital_name: "Lilavati Hospital",
      city: "Mumbai",
      state: "Maharashtra",
    },
    consultation_fee: 1600,
    consultation_mode: "both",
    avg_rating: 4.6,
    total_reviews: 420,
    patients_treated: 1200,
    verified: true,
  },

  // ================= GASTRO =================
  {
    doctor_id: "D07",
    doctor_name: "Dr. Sameer Gupta",
    image: "/uploads/doctors/d7.jpeg",
    specialization: "Gastroenterologist",
    treatment: "Liver Transplant",
    experience_years: 20,
    hospital: {
      hospital_id: "H002",
      hospital_name: "Lilavati Hospital",
      city: "Mumbai",
      state: "Maharashtra",
    },
    consultation_fee: 1400,
    consultation_mode: "offline",
    avg_rating: 4.8,
    total_reviews: 1100,
    patients_treated: 8200,
    verified: true,
  },

  // ================= GYNECOLOGIST =================
  {
    doctor_id: "D05",
    doctor_name: "Dr. Anjali Deshmukh",
    image: "/uploads/doctors/d5.jpeg",
    specialization: "Gynecologist",
    treatment: "Normal Delivery",
    experience_years: 14,
    hospital: {
      hospital_id: "H002",
      hospital_name: "Lilavati Hospital",
      city: "Mumbai",
      state: "Maharashtra",
    },
    consultation_fee: 1100,
    consultation_mode: "both",
    avg_rating: 4.9,
    total_reviews: 1800,
    patients_treated: 6000,
    verified: true,
  },

  // ================= PEDIATRICIAN =================
  {
    doctor_id: "D06",
    doctor_name: "Dr. Rohan Varma",
    image: "/uploads/doctors/d6.jpeg",
    specialization: "Pediatrician",
    treatment: "Vaccination",
    experience_years: 9,
    hospital: {
      hospital_id: "H002",
      hospital_name: "Lilavati Hospital",
      city: "Mumbai",
      state: "Maharashtra",
    },
    consultation_fee: 700,
    consultation_mode: "both",
    avg_rating: 4.7,
    total_reviews: 950,
    patients_treated: 3500,
    verified: true,
  },
];

export default doctors;
