const moreDoctors = [
  // -------- CARDIOLOGISTS --------
  {
    doctor_id: "D51",
    doctor_name: "Dr. Arjun Mehra",
    image: "/uploads/doctors/d51.jpeg",
    specialization: "Cardiologist",
    treatment: "Angioplasty",
    experience_years: 18,
    hospital: {
      hospital_id: "H012",
      hospital_name: "Medanta Hospital",
      city: "Gurgaon",
      state: "Haryana",
    },
    consultation_fee: 1600,
    consultation_mode: "offline",
    avg_rating: 4.9,
    total_reviews: 2200,
    patients_treated: 10500,
    verified: true,
  },
  {
    doctor_id: "D52",
    doctor_name: "Dr. Neeraj Kulkarni",
    image: "/uploads/doctors/d52.jpeg",
    specialization: "Cardiologist",
    treatment: "Heart Bypass Surgery (CABG)",
    experience_years: 14,
    hospital: {
      hospital_id: "H013",
      hospital_name: "Ruby Hall Clinic",
      city: "Pune",
      state: "Maharashtra",
    },
    consultation_fee: 1200,
    consultation_mode: "both",
    avg_rating: 4.7,
    total_reviews: 980,
    patients_treated: 4800,
    verified: true,
  },

  // -------- NEUROLOGISTS --------
  {
    doctor_id: "D53",
    doctor_name: "Dr. Ishita Banerjee",
    image: "/uploads/doctors/d53.jpeg",
    specialization: "Neurologist",
    treatment: "Brain Tumor Surgery",
    experience_years: 12,
    hospital: {
      hospital_id: "H014",
      hospital_name: "AMRI Hospital",
      city: "Kolkata",
      state: "West Bengal",
    },
    consultation_fee: 1300,
    consultation_mode: "both",
    avg_rating: 4.8,
    total_reviews: 750,
    patients_treated: 3900,
    verified: true,
  },
  {
    doctor_id: "D54",
    doctor_name: "Dr. Rohit Menon",
    image: "/uploads/doctors/d54.jpeg",
    specialization: "Neurologist",
    treatment: "Spinal Fusion Surgery",
    experience_years: 20,
    hospital: {
      hospital_id: "H015",
      hospital_name: "AIMS Kochi",
      city: "Kochi",
      state: "Kerala",
    },
    consultation_fee: 1500,
    consultation_mode: "offline",
    avg_rating: 4.9,
    total_reviews: 1800,
    patients_treated: 8200,
    verified: true,
  },

  // -------- ORTHOPEDIC --------
  {
    doctor_id: "D55",
    doctor_name: "Dr. Tushar Jain",
    image: "/uploads/doctors/d55.jpeg",
    specialization: "Orthopedic",
    treatment: "Knee Replacement",
    experience_years: 16,
    hospital: {
      hospital_id: "H016",
      hospital_name: "Global Hospital",
      city: "Chennai",
      state: "Tamil Nadu",
    },
    consultation_fee: 1100,
    consultation_mode: "both",
    avg_rating: 4.7,
    total_reviews: 1350,
    patients_treated: 6100,
    verified: true,
  },
  {
    doctor_id: "D56",
    doctor_name: "Dr. Kavish Arora",
    image: "/uploads/doctors/d56.jpeg",
    specialization: "Orthopedic",
    treatment: "Hip Replacement",
    experience_years: 13,
    hospital: {
      hospital_id: "H017",
      hospital_name: "Columbia Asia",
      city: "Noida",
      state: "Uttar Pradesh",
    },
    consultation_fee: 1000,
    consultation_mode: "offline",
    avg_rating: 4.6,
    total_reviews: 890,
    patients_treated: 4200,
    verified: true,
  },

  // -------- GASTROENTEROLOGIST --------
  {
    doctor_id: "D57",
    doctor_name: "Dr. Sameera Pillai",
    image: "/uploads/doctors/d57.jpeg",
    specialization: "Gastroenterologist",
    treatment: "Liver Transplant",
    experience_years: 15,
    hospital: {
      hospital_id: "H018",
      hospital_name: "Care Hospital",
      city: "Visakhapatnam",
      state: "Andhra Pradesh",
    },
    consultation_fee: 1400,
    consultation_mode: "offline",
    avg_rating: 4.8,
    total_reviews: 950,
    patients_treated: 5000,
    verified: true,
  },

  // -------- UROLOGIST (Kidney Transplant) --------
  {
    doctor_id: "D58",
    doctor_name: "Dr. Akash Verma",
    image: "/uploads/doctors/d58.jpeg",
    specialization: "Urologist",
    treatment: "Kidney Transplant",
    experience_years: 17,
    hospital: {
      hospital_id: "H019",
      hospital_name: "Tata Memorial Hospital",
      city: "Mumbai",
      state: "Maharashtra",
    },
    consultation_fee: 1800,
    consultation_mode: "offline",
    avg_rating: 4.9,
    total_reviews: 3000,
    patients_treated: 6700,
    verified: true,
  },

  // -------- OPHTHALMOLOGIST --------
  {
    doctor_id: "D59",
    doctor_name: "Dr. Priyanka Shah",
    image: "/uploads/doctors/d59.jpeg",
    specialization: "Ophthalmologist",
    treatment: "Cataract Surgery",
    experience_years: 15,
    hospital: {
      hospital_id: "H020",
      hospital_name: "LV Prasad Eye Institute",
      city: "Hyderabad",
      state: "Telangana",
    },
    consultation_fee: 900,
    consultation_mode: "offline",
    avg_rating: 4.9,
    total_reviews: 2100,
    patients_treated: 8800,
    verified: true,
  },
  {
    doctor_id: "D60",
    doctor_name: "Dr. Ritu Arora",
    image: "/uploads/doctors/d60.jpeg",
    specialization: "Ophthalmologist",
    treatment: "LASIK Eye Surgery",
    experience_years: 11,
    hospital: {
      hospital_id: "H021",
      hospital_name: "Cloudnine Hospital",
      city: "Delhi",
      state: "Delhi",
    },
    consultation_fee: 1300,
    consultation_mode: "both",
    avg_rating: 4.8,
    total_reviews: 1400,
    patients_treated: 7200,
    verified: true,
  },

  // -------- ONCOLOGIST --------
  {
    doctor_id: "D61",
    doctor_name: "Dr. Abhishek Nanda",
    image: "/uploads/doctors/d61.jpeg",
    specialization: "Oncologist",
    treatment: "Chemotherapy (Per Cycle)",
    experience_years: 12,
    hospital: {
      hospital_id: "H022",
      hospital_name: "Rainbow Cancer Institute",
      city: "Hyderabad",
      state: "Telangana",
    },
    consultation_fee: 1500,
    consultation_mode: "both",
    avg_rating: 4.9,
    total_reviews: 1600,
    patients_treated: 5100,
    verified: true,
  },

  // -------- GENERAL SURGEON --------
  {
    doctor_id: "D62",
    doctor_name: "Dr. Kunal Sharma",
    image: "/uploads/doctors/d62.jpeg",
    specialization: "General Surgeon",
    treatment: "Appendix Surgery",
    experience_years: 10,
    hospital: {
      hospital_id: "H023",
      hospital_name: "Sterling Hospital",
      city: "Ahmedabad",
      state: "Gujarat",
    },
    consultation_fee: 800,
    consultation_mode: "offline",
    avg_rating: 4.7,
    total_reviews: 620,
    patients_treated: 2900,
    verified: true,
  },
];

export default moreDoctors;
