const hospitals = [
  {
    hospital_id: "H001",
    hospital_name: "Apollo Hospitals",
    hospital_type: "Private",
    city: "Pune",
    state: "Maharashtra",
    country: "India",
    address: "Baner Road, Pune",
    contact_number: "9876543210",
    email: "info@apollo.com",
    facilities: ["ICU", "MRI", "CT", "Labs"],
    total_doctors: 180,
    avg_rating: 4.5,
    doctors_id: {},
  },
  {
    hospital_id: "H002",
    hospital_name: "Fortis Hospital",
    hospital_type: "Private",
    city: "Mumbai",
    state: "Maharashtra",
    country: "India",
    address: "Mulund West, Mumbai",
    contact_number: "9123456780",
    email: "contact@fortis.com",
    facilities: ["ICU", "Cath Lab", "MRI"],
    total_doctors: 150,
    avg_rating: 4.4,
    doctors_id: {},
  },
  {
    hospital_id: "H003",
    hospital_name: "Ruby Hall Clinic",
    hospital_type: "Private",
    city: "Pune",
    state: "Maharashtra",
    country: "India",
    address: "Sassoon Road, Pune",
    contact_number: "9988776655",
    email: "care@rubyhall.com",
    facilities: ["ICU", "CT", "Emergency"],
    total_doctors: 120,
    avg_rating: 4.3,
    doctors_id: {},
  },
  {
    hospital_id: "H004",
    hospital_name: "AIIMS Delhi",
    hospital_type: "Government",
    city: "Delhi",
    state: "Delhi",
    country: "India",
    address: "Ansari Nagar, Delhi",
    contact_number: "9012345678",
    email: "info@aiims.edu",
    facilities: ["ICU", "Trauma Center", "Labs"],
    total_doctors: 300,
    avg_rating: 4.6,
    doctors_id: {},
  },
  {
    hospital_id: "H005",
    hospital_name: "KEM Hospital",
    hospital_type: "Government",
    city: "Mumbai",
    state: "Maharashtra",
    country: "India",
    address: "Parel, Mumbai",
    contact_number: "9345678123",
    email: "kem@gov.in",
    facilities: ["ICU", "Blood Bank", "MRI"],
    total_doctors: 250,
    avg_rating: 4.2,
    doctors_id: {},
  },
  {
    hospital_id: "H006",
    hospital_name: "Manipal Hospital",
    hospital_type: "Private",
    city: "Bengaluru",
    state: "Karnataka",
    country: "India",
    address: "Old Airport Road, Bengaluru",
    contact_number: "9456123789",
    email: "support@manipalhospitals.com",
    facilities: ["ICU", "MRI", "Dialysis"],
    total_doctors: 160,
    avg_rating: 4.4,
    doctors_id: {},
  },
  {
    hospital_id: "H007",
    hospital_name: "Narayana Health",
    hospital_type: "Private",
    city: "Chennai",
    state: "Tamil Nadu",
    country: "India",
    address: "Adyar, Chennai",
    contact_number: "9765432189",
    email: "info@narayanahealth.org",
    facilities: ["ICU", "Cath Lab", "Labs"],
    total_doctors: 140,
    avg_rating: 4.3,
    doctors_id: {},
  },
  {
    hospital_id: "H008",
    hospital_name: "Yashoda Hospital",
    hospital_type: "Private",
    city: "Hyderabad",
    state: "Telangana",
    country: "India",
    address: "Secunderabad, Hyderabad",
    contact_number: "9898989898",
    email: "help@yashodahospitals.com",
    facilities: ["ICU", "MRI", "Emergency"],
    total_doctors: 130,
    avg_rating: 4.5,
    doctors_id: {},
  },
  {
    hospital_id: "H009",
    hospital_name: "Government Medical College",
    hospital_type: "Government",
    city: "Nagpur",
    state: "Maharashtra",
    country: "India",
    address: "Hanuman Nagar, Nagpur",
    contact_number: "9123987654",
    email: "gmc_nagpur@gov.in",
    facilities: ["ICU", "OPD", "Labs"],
    total_doctors: 110,
    avg_rating: 4.0,
    doctors_id: {},
  },
  {
    hospital_id: "H010",
    hospital_name: "Max Super Speciality Hospital",
    hospital_type: "Private",
    city: "Delhi",
    state: "Delhi",
    country: "India",
    address: "Saket, Delhi",
    contact_number: "9001234567",
    email: "info@maxhealthcare.com",
    facilities: ["ICU", "Oncology", "MRI"],
    total_doctors: 170,
    avg_rating: 4.4,
    doctors_id: {},
  },
  {
    hospital_id: "H011",
    hospital_name: "Sunrise Multispeciality Hospital",
    hospital_type: "Private",
    city: "Ahmedabad",
    state: "Gujarat",
    country: "India",
    address: "SG Highway, Ahmedabad",
    contact_number: "9812345670",
    email: "contact@sunrisehospital.com",
    facilities: ["ICU", "MRI", "Emergency", "Labs"],
    total_doctors: 95,
    avg_rating: 4.2,
    doctors_id: {},
  },
  {
    hospital_id: "H012",
    hospital_name: "City Care Hospital",
    hospital_type: "Private",
    city: "Indore",
    state: "Madhya Pradesh",
    country: "India",
    address: "Vijay Nagar, Indore",
    contact_number: "9823456711",
    email: "info@citycareindore.com",
    facilities: ["ICU", "CT", "Dialysis"],
    total_doctors: 80,
    avg_rating: 4.1,
    doctors_id: {},
  },
  {
    hospital_id: "H013",
    hospital_name: "Lotus Hospital",
    hospital_type: "Private",
    city: "Jaipur",
    state: "Rajasthan",
    country: "India",
    address: "Malviya Nagar, Jaipur",
    contact_number: "9834567122",
    email: "support@lotushospital.com",
    facilities: ["ICU", "Emergency", "MRI"],
    total_doctors: 105,
    avg_rating: 4.3,
    doctors_id: {},
  },
  {
    hospital_id: "H014",
    hospital_name: "Sanjeevani Hospital",
    hospital_type: "Private",
    city: "Kolhapur",
    state: "Maharashtra",
    country: "India",
    address: "Shivaji Nagar, Kolhapur",
    contact_number: "9845671233",
    email: "help@sanjeevanihospital.com",
    facilities: ["ICU", "OPD", "Labs"],
    total_doctors: 60,
    avg_rating: 4.0,
    doctors_id: {},
  },
  {
    hospital_id: "H015",
    hospital_name: "Sharda Medical Center",
    hospital_type: "Private",
    city: "Greater Noida",
    state: "Uttar Pradesh",
    country: "India",
    address: "Knowledge Park, Greater Noida",
    contact_number: "9856782344",
    email: "info@shardamedical.com",
    facilities: ["ICU", "Trauma", "MRI"],
    total_doctors: 140,
    avg_rating: 4.4,
    doctors_id: {},
  },
  {
    hospital_id: "H016",
    hospital_name: "District Civil Hospital",
    hospital_type: "Government",
    city: "Surat",
    state: "Gujarat",
    country: "India",
    address: "Ring Road, Surat",
    contact_number: "9867893455",
    email: "civilhospital.surat@gov.in",
    facilities: ["ICU", "OPD", "Emergency"],
    total_doctors: 110,
    avg_rating: 3.9,
    doctors_id: {},
  },
  {
    hospital_id: "H017",
    hospital_name: "Green Valley Hospital",
    hospital_type: "Private",
    city: "Dehradun",
    state: "Uttarakhand",
    country: "India",
    address: "Rajpur Road, Dehradun",
    contact_number: "9878904566",
    email: "info@greenvalleyhospital.com",
    facilities: ["ICU", "MRI", "Dialysis"],
    total_doctors: 85,
    avg_rating: 4.2,
    doctors_id: {},
  },
  {
    hospital_id: "H018",
    hospital_name: "LifeLine Super Speciality Hospital",
    hospital_type: "Private",
    city: "Vijayawada",
    state: "Andhra Pradesh",
    country: "India",
    address: "Benz Circle, Vijayawada",
    contact_number: "9889015677",
    email: "care@lifelinehospital.com",
    facilities: ["ICU", "Cath Lab", "Emergency"],
    total_doctors: 125,
    avg_rating: 4.3,
    doctors_id: {},
  },
  {
    hospital_id: "H019",
    hospital_name: "Government General Hospital",
    hospital_type: "Government",
    city: "Tirupati",
    state: "Andhra Pradesh",
    country: "India",
    address: "SV Road, Tirupati",
    contact_number: "9890126788",
    email: "ggh_tirupati@gov.in",
    facilities: ["ICU", "OPD", "Blood Bank"],
    total_doctors: 135,
    avg_rating: 4.0,
    doctors_id: {},
  },
  {
    hospital_id: "H020",
    hospital_name: "Hope Multispeciality Hospital",
    hospital_type: "Private",
    city: "Kochi",
    state: "Kerala",
    country: "India",
    address: "MG Road, Kochi",
    contact_number: "9901237899",
    email: "support@hopehospital.com",
    facilities: ["ICU", "MRI", "Emergency"],
    total_doctors: 115,
    avg_rating: 4.4,
    doctors_id: {},
  },
  {
    hospital_id: "H021",
    hospital_name: "New Life Hospital",
    hospital_type: "Private",
    city: "Patna",
    state: "Bihar",
    country: "India",
    address: "Boring Road, Patna",
    contact_number: "9912348900",
    email: "info@newlifehospital.com",
    facilities: ["ICU", "CT", "Labs"],
    total_doctors: 90,
    avg_rating: 4.1,
    doctors_id: {},
  },
  {
    hospital_id: "H022",
    hospital_name: "Metro Heart Institute",
    hospital_type: "Private",
    city: "Faridabad",
    state: "Haryana",
    country: "India",
    address: "Sector 16, Faridabad",
    contact_number: "9923459011",
    email: "care@metroheart.com",
    facilities: ["ICU", "Cath Lab", "Cardiology"],
    total_doctors: 100,
    avg_rating: 4.3,
    doctors_id: {},
  },
  {
    hospital_id: "H023",
    hospital_name: "Blue Cross Hospital",
    hospital_type: "Private",
    city: "Chandigarh",
    state: "Chandigarh",
    country: "India",
    address: "Sector 22, Chandigarh",
    contact_number: "9934560122",
    email: "info@bluecrosshospital.com",
    facilities: ["ICU", "MRI", "Emergency"],
    total_doctors: 88,
    avg_rating: 4.2,
    doctors_id: {},
  },
  {
    hospital_id: "H024",
    hospital_name: "Care & Cure Hospital",
    hospital_type: "Private",
    city: "Udaipur",
    state: "Rajasthan",
    country: "India",
    address: "Hiran Magri, Udaipur",
    contact_number: "9945671234",
    email: "help@carecurehospital.com",
    facilities: ["ICU", "OPD", "Labs"],
    total_doctors: 70,
    avg_rating: 4.0,
    doctors_id: {},
  },
  {
    hospital_id: "H025",
    hospital_name: "Unity Hospital",
    hospital_type: "Government",
    city: "Vadodara",
    state: "Gujarat",
    country: "India",
    address: "Alkapuri, Vadodara",
    contact_number: "9956782345",
    email: "unityhospital@gov.in",
    facilities: ["ICU", "Emergency", "Blood Bank"],
    total_doctors: 145,
    avg_rating: 4.1,
    doctors_id: {},
  },
  {
    hospital_id: "H026",
    hospital_name: "Silver Line Hospital",
    hospital_type: "Private",
    city: "Noida",
    state: "Uttar Pradesh",
    country: "India",
    address: "Sector 62, Noida",
    contact_number: "9967893456",
    email: "info@silverlinehospital.com",
    facilities: ["ICU", "MRI", "Dialysis"],
    total_doctors: 130,
    avg_rating: 4.4,
    doctors_id: {},
  },
  {
    hospital_id: "H027",
    hospital_name: "Healing Touch Hospital",
    hospital_type: "Private",
    city: "Jodhpur",
    state: "Rajasthan",
    country: "India",
    address: "Paota, Jodhpur",
    contact_number: "9978904567",
    email: "care@healingtouch.com",
    facilities: ["ICU", "CT", "Emergency"],
    total_doctors: 75,
    avg_rating: 4.1,
    doctors_id: {},
  },
  {
    hospital_id: "H028",
    hospital_name: "Pragati Government Hospital",
    hospital_type: "Government",
    city: "Raipur",
    state: "Chhattisgarh",
    country: "India",
    address: "Civil Lines, Raipur",
    contact_number: "9989015678",
    email: "pragati_hospital@gov.in",
    facilities: ["ICU", "OPD", "Labs"],
    total_doctors: 120,
    avg_rating: 3.8,
    doctors_id: {},
  },
  {
    hospital_id: "H029",
    hospital_name: "Wellness Multispeciality Hospital",
    hospital_type: "Private",
    city: "Siliguri",
    state: "West Bengal",
    country: "India",
    address: "Hill Cart Road, Siliguri",
    contact_number: "9990126789",
    email: "info@wellnesshospital.com",
    facilities: ["ICU", "MRI", "Emergency"],
    total_doctors: 85,
    avg_rating: 4.2,
    doctors_id: {},
  },
  {
    hospital_id: "H030",
    hospital_name: "North East Medical Institute",
    hospital_type: "Government",
    city: "Guwahati",
    state: "Assam",
    country: "India",
    address: "GS Road, Guwahati",
    contact_number: "9001237890",
    email: "nemi_guwahati@gov.in",
    facilities: ["ICU", "Trauma", "Labs"],
    total_doctors: 160,
    avg_rating: 4.1,
    doctors_id: {},
  },
];

export default hospitals;
