const hospitals = [
  {
    hospital_id: "H001",
    hospital_name: "Apollo Hospitals",
    hospital_type: "Private",
    description:
      "Multi-specialty hospital providing advanced healthcare services.",
    location: {
      address: "Baner Road",
      city: "Pune",
      state: "Maharashtra",
      country: "India",
      pincode: "411045",
    },
    contact: { phone: "9876543210", email: "info@apollo.com" },
    facilities: ["ICU", "MRI", "CT Scan", "Pathology Lab", "Pharmacy"],
    specializations: ["Cardiology", "Neurology", "Orthopedics", "Pediatrics"],
    hospital_stats: {
      total_doctors: 180,
      bed_capacity: 250,
      icu_beds: 40,
      operation_theatres: 8,
    },
    services: {
      emergency_24x7: true,
      ambulance_service: true,
      online_appointment: true,
      blood_bank_available: true,
      insurance_accepted: ["Star Health", "HDFC ERGO", "ICICI Lombard"],
    },
    timing: { opening_time: "08:00 AM", closing_time: "08:00 PM" },
    ratings: { avg_rating: 4.5, total_reviews: 1280 },
    graph: {
      success_rate: 92,
      hospital_rating: 84,
      doctors_rating: 95,
      average_rating: 89,
    },
    reviews: [
      {
        patient_name: "Rahul Sharma",
        rating: 5,
        comment: "Excellent treatment.",
      },
      { patient_name: "Priya Patil", rating: 4, comment: "Good facilities." },
    ],
    image: "/uploads/hospitals/h1.jpeg",
  },

  {
    hospital_id: "H002",
    hospital_name: "Fortis Memorial",
    hospital_type: "Private",
    description: "A premier multi-speciality tertiary care hospital.",
    location: {
      address: "Sector 44",
      city: "Gurugram",
      state: "Haryana",
      country: "India",
      pincode: "122002",
    },
    contact: { phone: "9822113344", email: "contact@fortis.com" },
    facilities: ["ICU", "Pet-CT", "Dialysis", "Blood Bank"],
    specializations: ["Oncology", "Nephrology", "Pulmonology"],
    hospital_stats: {
      total_doctors: 150,
      bed_capacity: 300,
      icu_beds: 55,
      operation_theatres: 10,
    },
    services: {
      emergency_24x7: true,
      ambulance_service: true,
      online_appointment: true,
      blood_bank_available: true,
      insurance_accepted: ["Religare", "Max Bupa"],
    },
    timing: { opening_time: "09:00 AM", closing_time: "09:00 PM" },
    ratings: { avg_rating: 4.2, total_reviews: 950 },
    graph: {
      success_rate: 88,
      hospital_rating: 80,
      doctors_rating: 92,
      average_rating: 86,
    },
    reviews: [
      {
        patient_name: "Amit Goel",
        rating: 4,
        comment: "Very professional doctors.",
      },
    ],
    image: "/uploads/hospitals/h2.jpeg",
  },

  {
    hospital_id: "H003",
    hospital_name: "AIIMS Delhi",
    hospital_type: "Government",
    description: "Premier public medical research university and hospital.",
    location: {
      address: "Ansari Nagar",
      city: "New Delhi",
      state: "Delhi",
      country: "India",
      pincode: "110029",
    },
    contact: { phone: "011-26588500", email: "director@aiims.edu" },
    facilities: ["Trauma Center", "Emergency", "Research Lab", "Free Pharmacy"],
    specializations: ["General Surgery", "Cardiology", "Dermatology"],
    hospital_stats: {
      total_doctors: 800,
      bed_capacity: 2200,
      icu_beds: 150,
      operation_theatres: 25,
    },
    services: {
      emergency_24x7: true,
      ambulance_service: true,
      online_appointment: true,
      blood_bank_available: true,
      insurance_accepted: ["CGHS", "ECHS"],
    },
    timing: { opening_time: "00:00 AM", closing_time: "11:59 PM" },
    ratings: { avg_rating: 4.0, total_reviews: 5000 },
    graph: {
      success_rate: 95,
      hospital_rating: 75,
      doctors_rating: 98,
      average_rating: 85,
    },
    reviews: [
      {
        patient_name: "Suresh Kumar",
        rating: 5,
        comment: "Best doctors in the country.",
      },
    ],
    image: "/uploads/hospitals/h3.jpeg",
  },

  {
    hospital_id: "H004",
    hospital_name: "Manipal Hospital",
    hospital_type: "Private",
    description: "Patient-centric healthcare with world-class amenities.",
    location: {
      address: "HAL Airport Road",
      city: "Bangalore",
      state: "Karnataka",
      country: "India",
      pincode: "560017",
    },
    contact: { phone: "8025024444", email: "info@manipalhospitals.com" },
    facilities: ["24/7 Pharmacy", "Advanced OT", "Rehabilitation"],
    specializations: ["Orthopedics", "Urology", "IVF", "ENT"],
    hospital_stats: {
      total_doctors: 110,
      bed_capacity: 280,
      icu_beds: 35,
      operation_theatres: 7,
    },
    services: {
      emergency_24x7: true,
      ambulance_service: true,
      online_appointment: true,
      blood_bank_available: true,
      insurance_accepted: ["Star Health", "Bajaj Allianz"],
    },
    timing: { opening_time: "08:00 AM", closing_time: "09:00 PM" },
    ratings: { avg_rating: 4.6, total_reviews: 1100 },
    graph: {
      success_rate: 93,
      hospital_rating: 88,
      doctors_rating: 94,
      average_rating: 91,
    },
    reviews: [
      {
        patient_name: "Megha Rao",
        rating: 5,
        comment: "Excellent nursing care.",
      },
    ],
    image: "/uploads/hospitals/h4.jpeg",
  },

  {
    hospital_id: "H005",
    hospital_name: "Kokilaben Dhirubhai Ambani",
    hospital_type: "Private",
    description: "State-of-the-art quaternary care hospital.",
    location: {
      address: "Four Bungalows",
      city: "Mumbai",
      state: "Maharashtra",
      country: "India",
      pincode: "400053",
    },
    contact: { phone: "022-30999999", email: "info.kh@relianceada.com" },
    facilities: ["Robot-assisted Surgery", "3T MRI", "Linear Accelerator"],
    specializations: ["Neurosurgery", "Cardiac Science", "Robotic Surgery"],
    hospital_stats: {
      total_doctors: 250,
      bed_capacity: 750,
      icu_beds: 180,
      operation_theatres: 22,
    },
    services: {
      emergency_24x7: true,
      ambulance_service: true,
      online_appointment: true,
      blood_bank_available: true,
      insurance_accepted: ["Aditya Birla", "Care Health"],
    },
    timing: { opening_time: "08:00 AM", closing_time: "10:00 PM" },
    ratings: { avg_rating: 4.8, total_reviews: 3200 },
    graph: {
      success_rate: 96,
      hospital_rating: 95,
      doctors_rating: 97,
      average_rating: 96,
    },
    reviews: [
      {
        patient_name: "Vikram Singh",
        rating: 5,
        comment: "Technologically very advanced.",
      },
    ],
    image: "/uploads/hospitals/h5.jpeg",
  },

  {
    hospital_id: "H006",
    hospital_name: "Medanta The Medicity",
    hospital_type: "Private",
    description:
      "Multi-specialty medical institute specializing in liver transplants.",
    location: {
      address: "CH Baktawar Singh Road",
      city: "Gurugram",
      state: "Haryana",
      country: "India",
      pincode: "122001",
    },
    contact: { phone: "0124-4141414", email: "info@medanta.org" },
    facilities: ["Organ Transplant", "Air Ambulance", "Lab Services"],
    specializations: ["Liver Transplant", "Cardiology", "Gastroenterology"],
    hospital_stats: {
      total_doctors: 300,
      bed_capacity: 1250,
      icu_beds: 300,
      operation_theatres: 45,
    },
    services: {
      emergency_24x7: true,
      ambulance_service: true,
      online_appointment: true,
      blood_bank_available: true,
      insurance_accepted: ["HDFC Ergo", "Max Bupa"],
    },
    timing: { opening_time: "09:00 AM", closing_time: "09:00 PM" },
    ratings: { avg_rating: 4.4, total_reviews: 2100 },
    graph: {
      success_rate: 91,
      hospital_rating: 89,
      doctors_rating: 94,
      average_rating: 91,
    },
    reviews: [
      {
        patient_name: "Rohan J.",
        rating: 4,
        comment: "Bit expensive but worth it.",
      },
    ],
    image: "/uploads/hospitals/h6.jpeg",
  },

  {
    hospital_id: "H007",
    hospital_name: "Lilavati Hospital",
    hospital_type: "Private",
    description: "Premier multi-specialty healthcare provider in Mumbai.",
    location: {
      address: "Bandra West",
      city: "Mumbai",
      state: "Maharashtra",
      country: "India",
      pincode: "400050",
    },
    contact: { phone: "022-26751000", email: "info@lilavatihospital.com" },
    facilities: ["Pathology", "Radiology", "Maternity Ward"],
    specializations: ["Endocrinology", "Gynecology", "Ophthalmology"],
    hospital_stats: {
      total_doctors: 140,
      bed_capacity: 320,
      icu_beds: 60,
      operation_theatres: 12,
    },
    services: {
      emergency_24x7: true,
      ambulance_service: true,
      online_appointment: true,
      blood_bank_available: true,
      insurance_accepted: ["Star Health", "Liberty"],
    },
    timing: { opening_time: "08:00 AM", closing_time: "09:00 PM" },
    ratings: { avg_rating: 4.3, total_reviews: 1500 },
    graph: {
      success_rate: 89,
      hospital_rating: 87,
      doctors_rating: 91,
      average_rating: 89,
    },
    reviews: [
      {
        patient_name: "Anjali K.",
        rating: 5,
        comment: "Excellent maternity care.",
      },
    ],
    image: "/uploads/hospitals/h7.jpeg",
  },

  {
    hospital_id: "H008",
    hospital_name: "Max Super Speciality",
    hospital_type: "Private",
    description: "Committed to clinical excellence and patient safety.",
    location: {
      address: "Saket",
      city: "New Delhi",
      state: "Delhi",
      country: "India",
      pincode: "110017",
    },
    contact: { phone: "011-26515050", email: "saket@maxhealthcare.com" },
    facilities: ["Chemotherapy", "Physiotherapy", "Dialysis Unit"],
    specializations: ["Oncology", "Joint Replacement", "Bariatric Surgery"],
    hospital_stats: {
      total_doctors: 200,
      bed_capacity: 500,
      icu_beds: 100,
      operation_theatres: 15,
    },
    services: {
      emergency_24x7: true,
      ambulance_service: true,
      online_appointment: true,
      blood_bank_available: true,
      insurance_accepted: ["United India", "Oriental"],
    },
    timing: { opening_time: "08:00 AM", closing_time: "10:00 PM" },
    ratings: { avg_rating: 4.1, total_reviews: 1800 },
    graph: {
      success_rate: 87,
      hospital_rating: 82,
      doctors_rating: 90,
      average_rating: 86,
    },
    reviews: [
      {
        patient_name: "Karan M.",
        rating: 4,
        comment: "Prompt emergency service.",
      },
    ],
    image: "/uploads/hospitals/h8.jpeg",
  },

  {
    hospital_id: "H009",
    hospital_name: "Christian Medical College (CMC)",
    hospital_type: "Trust",
    description: "Renowned for high-quality care and medical education.",
    location: {
      address: "Ida Scudder Road",
      city: "Vellore",
      state: "Tamil Nadu",
      country: "India",
      pincode: "632004",
    },
    contact: { phone: "0416-2281000", email: "director@cmcvellore.ac.in" },
    facilities: ["Low-cost care", "Research Center", "Rehabilitation"],
    specializations: ["Hematology", "Rheumatology", "Dermatology"],
    hospital_stats: {
      total_doctors: 600,
      bed_capacity: 2800,
      icu_beds: 200,
      operation_theatres: 35,
    },
    services: {
      emergency_24x7: true,
      ambulance_service: true,
      online_appointment: true,
      blood_bank_available: true,
      insurance_accepted: ["Government Schemes", "Self-Pay"],
    },
    timing: { opening_time: "07:00 AM", closing_time: "08:00 PM" },
    ratings: { avg_rating: 4.7, total_reviews: 8500 },
    graph: {
      success_rate: 94,
      hospital_rating: 90,
      doctors_rating: 98,
      average_rating: 94,
    },
    reviews: [
      {
        patient_name: "Sundar V.",
        rating: 5,
        comment: "Highly ethical and skilled doctors.",
      },
    ],
    image: "/uploads/hospitals/h9.jpeg",
  },

  {
    hospital_id: "H010",
    hospital_name: "Jaslok Hospital",
    hospital_type: "Private",
    description: "One of the oldest multi-specialty trust hospitals in Mumbai.",
    location: {
      address: "Pedder Road",
      city: "Mumbai",
      state: "Maharashtra",
      country: "India",
      pincode: "400026",
    },
    contact: { phone: "022-66573333", email: "info@jaslokhospital.net" },
    facilities: ["PET Scan", "Cath Lab", "Endoscopy"],
    specializations: ["Internal Medicine", "Nephrology", "Urology"],
    hospital_stats: {
      total_doctors: 130,
      bed_capacity: 360,
      icu_beds: 75,
      operation_theatres: 10,
    },
    services: {
      emergency_24x7: true,
      ambulance_service: true,
      online_appointment: true,
      blood_bank_available: true,
      insurance_accepted: ["New India Assurance", "Star Health"],
    },
    timing: { opening_time: "09:00 AM", closing_time: "09:00 PM" },
    ratings: { avg_rating: 4.2, total_reviews: 1100 },
    graph: {
      success_rate: 86,
      hospital_rating: 84,
      doctors_rating: 89,
      average_rating: 86,
    },
    reviews: [
      {
        patient_name: "Sita Ram",
        rating: 4,
        comment: "Good location and service.",
      },
    ],
    image: "/uploads/hospitals/h10.jpeg",
  },

  {
    hospital_id: "H011",
    hospital_name: "KIMS Hospital",
    hospital_type: "Private",
    description: "Leading multi-specialty care in South India.",
    location: {
      address: "Kondapur",
      city: "Hyderabad",
      state: "Telangana",
      country: "India",
      pincode: "500084",
    },
    contact: { phone: "040-44885000", email: "contact@kimshospitals.com" },
    facilities: ["Neuro-navigation", "ICU", "Lab"],
    specializations: ["Neurology", "Spine Surgery", "Cardiology"],
    hospital_stats: {
      total_doctors: 160,
      bed_capacity: 450,
      icu_beds: 90,
      operation_theatres: 14,
    },
    services: {
      emergency_24x7: true,
      ambulance_service: true,
      online_appointment: true,
      blood_bank_available: true,
      insurance_accepted: ["HDFC Ergo", "Star Health"],
    },
    timing: { opening_time: "08:00 AM", closing_time: "08:00 PM" },
    ratings: { avg_rating: 4.4, total_reviews: 980 },
    graph: {
      success_rate: 90,
      hospital_rating: 88,
      doctors_rating: 92,
      average_rating: 90,
    },
    reviews: [
      { patient_name: "Rajesh G.", rating: 5, comment: "Best neuro doctors." },
    ],
    image: "/uploads/hospitals/h11.jpeg",
  },

  {
    hospital_id: "H012",
    hospital_name: "Aster CMI Hospital",
    hospital_type: "Private",
    description: "Comprehensive healthcare with a global touch.",
    location: {
      address: "Hebbal",
      city: "Bangalore",
      state: "Karnataka",
      country: "India",
      pincode: "560092",
    },
    contact: { phone: "080-43420100", email: "info@asterhospitals.com" },
    facilities: ["Transplant Unit", "NICU", "Pharmacy"],
    specializations: ["Transplant Surgery", "Pediatrics", "Cardiology"],
    hospital_stats: {
      total_doctors: 120,
      bed_capacity: 500,
      icu_beds: 100,
      operation_theatres: 12,
    },
    services: {
      emergency_24x7: true,
      ambulance_service: true,
      online_appointment: true,
      blood_bank_available: true,
      insurance_accepted: ["Niva Bupa", "Cigna TTK"],
    },
    timing: { opening_time: "09:00 AM", closing_time: "09:00 PM" },
    ratings: { avg_rating: 4.5, total_reviews: 1400 },
    graph: {
      success_rate: 92,
      hospital_rating: 91,
      doctors_rating: 94,
      average_rating: 92,
    },
    reviews: [
      { patient_name: "Sunita D.", rating: 4, comment: "Very helpful staff." },
    ],
    image: "/uploads/hospitals/h12.jpeg",
  },

  {
    hospital_id: "H013",
    hospital_name: "Sir H. N. Reliance Foundation",
    hospital_type: "Private",
    description: "Modern healthcare combined with a legacy of care.",
    location: {
      address: "Girgaon",
      city: "Mumbai",
      state: "Maharashtra",
      country: "India",
      pincode: "400004",
    },
    contact: { phone: "1800-221-166", email: "info@rfhospital.org" },
    facilities: ["Robotic Surgery", "Genetic Lab", "ICU"],
    specializations: ["Genetics", "Orthopedics", "Cardiology"],
    hospital_stats: {
      total_doctors: 210,
      bed_capacity: 345,
      icu_beds: 80,
      operation_theatres: 11,
    },
    services: {
      emergency_24x7: true,
      ambulance_service: true,
      online_appointment: true,
      blood_bank_available: true,
      insurance_accepted: ["All Major Insurers"],
    },
    timing: { opening_time: "08:00 AM", closing_time: "10:00 PM" },
    ratings: { avg_rating: 4.9, total_reviews: 2200 },
    graph: {
      success_rate: 97,
      hospital_rating: 96,
      doctors_rating: 98,
      average_rating: 97,
    },
    reviews: [
      {
        patient_name: "Sandeep L.",
        rating: 5,
        comment: "Luxury and health together.",
      },
    ],
    image: "/uploads/hospitals/h13.jpeg",
  },

  {
    hospital_id: "H014",
    hospital_name: "Amrita Hospital",
    hospital_type: "Trust",
    description: "One of the largest hospitals in South Asia.",
    location: {
      address: "Ponekkara",
      city: "Kochi",
      state: "Kerala",
      country: "India",
      pincode: "682041",
    },
    contact: { phone: "0484-2851234", email: "hospital@aims.amrita.edu" },
    facilities: ["Telemedicine", "Research Lab", "Nuclear Medicine"],
    specializations: ["Nano Medicine", "Oncology", "Pediatric Surgery"],
    hospital_stats: {
      total_doctors: 400,
      bed_capacity: 1300,
      icu_beds: 250,
      operation_theatres: 28,
    },
    services: {
      emergency_24x7: true,
      ambulance_service: true,
      online_appointment: true,
      blood_bank_available: true,
      insurance_accepted: ["Government Schemes", "Star"],
    },
    timing: { opening_time: "00:00 AM", closing_time: "11:59 PM" },
    ratings: { avg_rating: 4.6, total_reviews: 3100 },
    graph: {
      success_rate: 93,
      hospital_rating: 92,
      doctors_rating: 95,
      average_rating: 93,
    },
    reviews: [
      {
        patient_name: "Rahul V.",
        rating: 5,
        comment: "Outstanding charity work.",
      },
    ],
    image: "/uploads/hospitals/h14.jpeg",
  },

  {
    hospital_id: "H015",
    hospital_name: "Artemis Hospital",
    hospital_type: "Private",
    description: "First JCI & NABH accredited hospital in Gurugram.",
    location: {
      address: "Sector 51",
      city: "Gurugram",
      state: "Haryana",
      country: "India",
      pincode: "122001",
    },
    contact: { phone: "0124-4511111", email: "info@artemishospitals.com" },
    facilities: ["Trauma Center", "MRI", "Blood Bank"],
    specializations: ["Critical Care", "Cardiology", "Neurology"],
    hospital_stats: {
      total_doctors: 170,
      bed_capacity: 400,
      icu_beds: 85,
      operation_theatres: 12,
    },
    services: {
      emergency_24x7: true,
      ambulance_service: true,
      online_appointment: true,
      blood_bank_available: true,
      insurance_accepted: ["Religare", "HDFC"],
    },
    timing: { opening_time: "08:30 AM", closing_time: "09:30 PM" },
    ratings: { avg_rating: 4.2, total_reviews: 1250 },
    graph: {
      success_rate: 89,
      hospital_rating: 85,
      doctors_rating: 91,
      average_rating: 88,
    },
    reviews: [
      { patient_name: "Pawan K.", rating: 4, comment: "Good infrastructure." },
    ],
    image: "/uploads/hospitals/h15.jpeg",
  },

  {
    hospital_id: "H016",
    hospital_name: "Gleneagles Global",
    hospital_type: "Private",
    description: "Pioneers in multi-organ transplants.",
    location: {
      address: "Lakdi-ka-pul",
      city: "Hyderabad",
      state: "Telangana",
      country: "India",
      pincode: "500004",
    },
    contact: { phone: "040-23244444", email: "info@globalhospitalsindia.com" },
    facilities: ["Organ Transplant", "Dialysis", "CT Scan"],
    specializations: ["Liver Disease", "Nephrology", "Pulmonology"],
    hospital_stats: {
      total_doctors: 105,
      bed_capacity: 300,
      icu_beds: 60,
      operation_theatres: 8,
    },
    services: {
      emergency_24x7: true,
      ambulance_service: true,
      online_appointment: true,
      blood_bank_available: true,
      insurance_accepted: ["Star Health", "Max Bupa"],
    },
    timing: { opening_time: "09:00 AM", closing_time: "08:00 PM" },
    ratings: { avg_rating: 4.3, total_reviews: 890 },
    graph: {
      success_rate: 91,
      hospital_rating: 86,
      doctors_rating: 93,
      average_rating: 90,
    },
    reviews: [
      { patient_name: "Mohit S.", rating: 5, comment: "Excellent liver care." },
    ],
    image: "/uploads/hospitals/h16.jpeg",
  },

  {
    hospital_id: "H017",
    hospital_name: "Ruby Hall Clinic",
    hospital_type: "Private",
    description: "Pune's first NABH accredited hospital.",
    location: {
      address: "Sassoon Road",
      city: "Pune",
      state: "Maharashtra",
      country: "India",
      pincode: "411001",
    },
    contact: { phone: "020-66455100", email: "info@rubyhall.com" },
    facilities: ["Cancer Center", "Cardiac Lab", "MRI"],
    specializations: ["Oncology", "Cardiology", "IVF"],
    hospital_stats: {
      total_doctors: 190,
      bed_capacity: 600,
      icu_beds: 120,
      operation_theatres: 18,
    },
    services: {
      emergency_24x7: true,
      ambulance_service: true,
      online_appointment: true,
      blood_bank_available: true,
      insurance_accepted: ["Bajaj Allianz", "HDFC"],
    },
    timing: { opening_time: "08:00 AM", closing_time: "09:00 PM" },
    ratings: { avg_rating: 4.4, total_reviews: 2400 },
    graph: {
      success_rate: 90,
      hospital_rating: 88,
      doctors_rating: 91,
      average_rating: 90,
    },
    reviews: [
      {
        patient_name: "Arjun P.",
        rating: 4,
        comment: "Reliable and old trust.",
      },
    ],
    image: "/uploads/hospitals/h17.jpeg",
  },

  {
    hospital_id: "H018",
    hospital_name: "Narayana Health City",
    hospital_type: "Private",
    description: "Affordable quality healthcare for all.",
    location: {
      address: "Bommasandra",
      city: "Bangalore",
      state: "Karnataka",
      country: "India",
      pincode: "560099",
    },
    contact: { phone: "080-71222222", email: "info@narayanahealth.org" },
    facilities: ["Cardiac Excellence", "Bone Marrow Transplant", "ICU"],
    specializations: ["Pediatric Cardiology", "Hematology", "Cardiac Surgery"],
    hospital_stats: {
      total_doctors: 350,
      bed_capacity: 1000,
      icu_beds: 200,
      operation_theatres: 30,
    },
    services: {
      emergency_24x7: true,
      ambulance_service: true,
      online_appointment: true,
      blood_bank_available: true,
      insurance_accepted: ["Star", "Yeshasvini"],
    },
    timing: { opening_time: "08:00 AM", closing_time: "08:00 PM" },
    ratings: { avg_rating: 4.5, total_reviews: 4200 },
    graph: {
      success_rate: 94,
      hospital_rating: 89,
      doctors_rating: 96,
      average_rating: 93,
    },
    reviews: [
      {
        patient_name: "Laxmi N.",
        rating: 5,
        comment: "Saved my child's heart.",
      },
    ],
    image: "/uploads/hospitals/h18.jpeg",
  },

  {
    hospital_id: "H019",
    hospital_name: "Sahyadri Hospitals",
    hospital_type: "Private",
    description: "Largest chain of hospitals in Maharashtra.",
    location: {
      address: "Deccan Gymkhana",
      city: "Pune",
      state: "Maharashtra",
      country: "India",
      pincode: "411004",
    },
    contact: { phone: "020-67213000", email: "info@sahyadrihospital.com" },
    facilities: ["Neurology Lab", "Pathology", "24/7 Pharmacy"],
    specializations: ["Neurosciences", "Hematology", "Orthopedics"],
    hospital_stats: {
      total_doctors: 95,
      bed_capacity: 200,
      icu_beds: 45,
      operation_theatres: 6,
    },
    services: {
      emergency_24x7: true,
      ambulance_service: true,
      online_appointment: true,
      blood_bank_available: true,
      insurance_accepted: ["Star Health", "ICICI"],
    },
    timing: { opening_time: "09:00 AM", closing_time: "09:00 PM" },
    ratings: { avg_rating: 4.3, total_reviews: 1100 },
    graph: {
      success_rate: 88,
      hospital_rating: 85,
      doctors_rating: 92,
      average_rating: 88,
    },
    reviews: [
      { patient_name: "Vikas T.", rating: 4, comment: "Expert doctors." },
    ],
    image: "/uploads/hospitals/h19.jpeg",
  },

  {
    hospital_id: "H020",
    hospital_name: "TATA Memorial",
    hospital_type: "Government/Grant",
    description: "National comprehensive cancer center.",
    location: {
      address: "Parel",
      city: "Mumbai",
      state: "Maharashtra",
      country: "India",
      pincode: "400012",
    },
    contact: { phone: "022-24177000", email: "tmc@tmc.gov.in" },
    facilities: ["Radiotherapy", "Chemotherapy", "Palliative Care"],
    specializations: ["Oncology", "Radiology", "Cancer Surgery"],
    hospital_stats: {
      total_doctors: 500,
      bed_capacity: 700,
      icu_beds: 100,
      operation_theatres: 20,
    },
    services: {
      emergency_24x7: true,
      ambulance_service: false,
      online_appointment: true,
      blood_bank_available: true,
      insurance_accepted: ["PMJAY", "CGHS"],
    },
    timing: { opening_time: "09:00 AM", closing_time: "06:00 PM" },
    ratings: { avg_rating: 4.8, total_reviews: 9800 },
    graph: {
      success_rate: 85,
      hospital_rating: 80,
      doctors_rating: 99,
      average_rating: 88,
    },
    reviews: [
      {
        patient_name: "Harish P.",
        rating: 5,
        comment: "God sent for cancer patients.",
      },
    ],
    image: "/uploads/hospitals/h20.jpeg",
  },

  {
    hospital_id: "H021",
    hospital_name: "Cloudnine Hospital",
    hospital_type: "Private",
    description: "Specialized in maternity and childcare.",
    location: {
      address: "Jayanagar",
      city: "Bangalore",
      state: "Karnataka",
      country: "India",
      pincode: "560011",
    },
    contact: { phone: "1860-500-9999", email: "info@cloudninecare.com" },
    facilities: ["LDR Rooms", "NICU", "Stem Cell Banking"],
    specializations: ["Obstetrics", "Gynecology", "Neonatology"],
    hospital_stats: {
      total_doctors: 45,
      bed_capacity: 80,
      icu_beds: 15,
      operation_theatres: 3,
    },
    services: {
      emergency_24x7: true,
      ambulance_service: true,
      online_appointment: true,
      blood_bank_available: false,
      insurance_accepted: ["Niva Bupa", "Star"],
    },
    timing: { opening_time: "08:00 AM", closing_time: "08:00 PM" },
    ratings: { avg_rating: 4.7, total_reviews: 1600 },
    graph: {
      success_rate: 98,
      hospital_rating: 94,
      doctors_rating: 95,
      average_rating: 96,
    },
    reviews: [
      {
        patient_name: "Neha S.",
        rating: 5,
        comment: "Wonderful birth experience.",
      },
    ],
    image: "/uploads/hospitals/h21.jpeg",
  },

  {
    hospital_id: "H022",
    hospital_name: "Sankara Nethralaya",
    hospital_type: "Trust",
    description: "Leading eye hospital in India.",
    location: {
      address: "Nungambakkam",
      city: "Chennai",
      state: "Tamil Nadu",
      country: "India",
      pincode: "600006",
    },
    contact: { phone: "044-28271616", email: "information@snmail.org" },
    facilities: ["Eye Bank", "Lasik Center", "Contact Lens Clinic"],
    specializations: ["Ophthalmology", "Vitreo Retinal"],
    hospital_stats: {
      total_doctors: 120,
      bed_capacity: 200,
      icu_beds: 5,
      operation_theatres: 15,
    },
    services: {
      emergency_24x7: false,
      ambulance_service: false,
      online_appointment: true,
      blood_bank_available: false,
      insurance_accepted: ["Central Government", "State Govt"],
    },
    timing: { opening_time: "08:00 AM", closing_time: "06:00 PM" },
    ratings: { avg_rating: 4.6, total_reviews: 4500 },
    graph: {
      success_rate: 96,
      hospital_rating: 92,
      doctors_rating: 98,
      average_rating: 95,
    },
    reviews: [
      {
        patient_name: "Murugan R.",
        rating: 5,
        comment: "Best for eye surgeries.",
      },
    ],
    image: "/uploads/hospitals/h22.jpeg",
  },

  {
    hospital_id: "H023",
    hospital_name: "Nanavati Max Hospital",
    hospital_type: "Private",
    description: "Iconic hospital providing tertiary care.",
    location: {
      address: "Vile Parle",
      city: "Mumbai",
      state: "Maharashtra",
      country: "India",
      pincode: "400056",
    },
    contact: { phone: "022-26267500", email: "info@nanavatihospital.org" },
    facilities: ["MRI 3.0 Tesla", "Dialysis", "Pharmacy"],
    specializations: ["Gastroenterology", "Cardiology", "Neurology"],
    hospital_stats: {
      total_doctors: 155,
      bed_capacity: 350,
      icu_beds: 75,
      operation_theatres: 12,
    },
    services: {
      emergency_24x7: true,
      ambulance_service: true,
      online_appointment: true,
      blood_bank_available: true,
      insurance_accepted: ["Star Health", "Max Life"],
    },
    timing: { opening_time: "09:00 AM", closing_time: "09:00 PM" },
    ratings: { avg_rating: 4.1, total_reviews: 1900 },
    graph: {
      success_rate: 88,
      hospital_rating: 84,
      doctors_rating: 90,
      average_rating: 87,
    },
    reviews: [
      {
        patient_name: "Suresh P.",
        rating: 4,
        comment: "Very experienced doctors.",
      },
    ],
    image: "/uploads/hospitals/h23.jpeg",
  },

  {
    hospital_id: "H024",
    hospital_name: "Rainbow Children's Hospital",
    hospital_type: "Private",
    description: "Excellence in child care and women's health.",
    location: {
      address: "Banjara Hills",
      city: "Hyderabad",
      state: "Telangana",
      country: "India",
      pincode: "500034",
    },
    contact: { phone: "040-44464446", email: "info@rainbowhospitals.in" },
    facilities: ["PICU", "NICU", "Child Nutrition"],
    specializations: ["Pediatrics", "Neonatology", "Obstetrics"],
    hospital_stats: {
      total_doctors: 80,
      bed_capacity: 250,
      icu_beds: 60,
      operation_theatres: 5,
    },
    services: {
      emergency_24x7: true,
      ambulance_service: true,
      online_appointment: true,
      blood_bank_available: true,
      insurance_accepted: ["HDFC Ergo", "Star"],
    },
    timing: { opening_time: "08:00 AM", closing_time: "08:00 PM" },
    ratings: { avg_rating: 4.5, total_reviews: 2100 },
    graph: {
      success_rate: 95,
      hospital_rating: 90,
      doctors_rating: 93,
      average_rating: 92,
    },
    reviews: [
      { patient_name: "Kavita S.", rating: 5, comment: "Best for newborns." },
    ],
    image: "/uploads/hospitals/h24.jpeg",
  },

  {
    hospital_id: "H025",
    hospital_name: "AMRI Hospitals",
    hospital_type: "Private",
    description: "Top healthcare group in Eastern India.",
    location: {
      address: "Salt Lake",
      city: "Kolkata",
      state: "West Bengal",
      country: "India",
      pincode: "700098",
    },
    contact: { phone: "033-66800000", email: "info@amrihospitals.in" },
    facilities: ["Critical Care", "MRI", "Diagnostics"],
    specializations: ["Orthopedics", "Gastroenterology", "Urology"],
    hospital_stats: {
      total_doctors: 110,
      bed_capacity: 300,
      icu_beds: 50,
      operation_theatres: 8,
    },
    services: {
      emergency_24x7: true,
      ambulance_service: true,
      online_appointment: true,
      blood_bank_available: true,
      insurance_accepted: ["National Insurance", "Star"],
    },
    timing: { opening_time: "09:00 AM", closing_time: "09:00 PM" },
    ratings: { avg_rating: 4.0, total_reviews: 1300 },
    graph: {
      success_rate: 86,
      hospital_rating: 82,
      doctors_rating: 88,
      average_rating: 85,
    },
    reviews: [
      {
        patient_name: "Sourav D.",
        rating: 4,
        comment: "Good doctors, waiting time is high.",
      },
    ],
    image: "/uploads/hospitals/h25.jpeg",
  },

  {
    hospital_id: "H026",
    hospital_name: "MGM Healthcare",
    hospital_type: "Private",
    description: "Leading center for heart and lung transplants.",
    location: {
      address: "Aminjikarai",
      city: "Chennai",
      state: "Tamil Nadu",
      country: "India",
      pincode: "600029",
    },
    contact: { phone: "044-45242424", email: "info@mgmhealthcare.in" },
    facilities: ["Heart Transplant", "Lung Transplant", "ICU"],
    specializations: ["Cardiac Sciences", "Pulmonology", "Neurology"],
    hospital_stats: {
      total_doctors: 130,
      bed_capacity: 400,
      icu_beds: 100,
      operation_theatres: 12,
    },
    services: {
      emergency_24x7: true,
      ambulance_service: true,
      online_appointment: true,
      blood_bank_available: true,
      insurance_accepted: ["Care", "Star Health"],
    },
    timing: { opening_time: "09:00 AM", closing_time: "09:00 PM" },
    ratings: { avg_rating: 4.7, total_reviews: 1100 },
    graph: {
      success_rate: 92,
      hospital_rating: 94,
      doctors_rating: 96,
      average_rating: 94,
    },
    reviews: [
      {
        patient_name: "Krishnan T.",
        rating: 5,
        comment: "Highly advanced transplant center.",
      },
    ],
    image: "/uploads/hospitals/h26.jpeg",
  },

  {
    hospital_id: "H027",
    hospital_name: "Shalby Hospitals",
    hospital_type: "Private",
    description: "World leader in joint replacement surgery.",
    location: {
      address: "SG Highway",
      city: "Ahmedabad",
      state: "Gujarat",
      country: "India",
      pincode: "380015",
    },
    contact: { phone: "079-40203000", email: "info@shalby.org" },
    facilities: ["Joint Replacement Lab", "MRI", "Physiotherapy"],
    specializations: ["Orthopedics", "Knee Replacement", "Spine"],
    hospital_stats: {
      total_doctors: 90,
      bed_capacity: 200,
      icu_beds: 40,
      operation_theatres: 10,
    },
    services: {
      emergency_24x7: true,
      ambulance_service: true,
      online_appointment: true,
      blood_bank_available: true,
      insurance_accepted: ["Star Health", "HDFC"],
    },
    timing: { opening_time: "08:30 AM", closing_time: "08:30 PM" },
    ratings: { avg_rating: 4.4, total_reviews: 1800 },
    graph: {
      success_rate: 96,
      hospital_rating: 89,
      doctors_rating: 95,
      average_rating: 93,
    },
    reviews: [
      {
        patient_name: "Bhavin S.",
        rating: 5,
        comment: "Best for orthopedic issues.",
      },
    ],
    image: "/uploads/hospitals/h27.jpeg",
  },

  {
    hospital_id: "H028",
    hospital_name: "Continental Hospitals",
    hospital_type: "Private",
    description: "Global standards in tertiary care.",
    location: {
      address: "Gachibowli",
      city: "Hyderabad",
      state: "Telangana",
      country: "India",
      pincode: "500032",
    },
    contact: { phone: "040-67000000", email: "info@continentalhospitals.com" },
    facilities: ["Health Checkup", "Radiology", "Ambulance"],
    specializations: ["Gastroenterology", "Cardiology", "Neurology"],
    hospital_stats: {
      total_doctors: 140,
      bed_capacity: 750,
      icu_beds: 150,
      operation_theatres: 15,
    },
    services: {
      emergency_24x7: true,
      ambulance_service: true,
      online_appointment: true,
      blood_bank_available: true,
      insurance_accepted: ["All major insurers"],
    },
    timing: { opening_time: "09:00 AM", closing_time: "09:00 PM" },
    ratings: { avg_rating: 4.3, total_reviews: 1450 },
    graph: {
      success_rate: 90,
      hospital_rating: 91,
      doctors_rating: 92,
      average_rating: 91,
    },
    reviews: [
      {
        patient_name: "Ravi K.",
        rating: 4,
        comment: "Good facility and treatment.",
      },
    ],
    image: "/uploads/hospitals/h28.jpeg",
  },

  {
    hospital_id: "H029",
    hospital_name: "AIG Hospitals",
    hospital_type: "Private",
    description: "World-class center for gastroenterology.",
    location: {
      address: "Gachibowli",
      city: "Hyderabad",
      state: "Telangana",
      country: "India",
      pincode: "500032",
    },
    contact: { phone: "040-42444222", email: "info@aighospitals.com" },
    facilities: ["Endoscopy", "Liver Lab", "MRI"],
    specializations: ["Gastroenterology", "Hepatology", "Internal Medicine"],
    hospital_stats: {
      total_doctors: 180,
      bed_capacity: 800,
      icu_beds: 200,
      operation_theatres: 20,
    },
    services: {
      emergency_24x7: true,
      ambulance_service: true,
      online_appointment: true,
      blood_bank_available: true,
      insurance_accepted: ["Star Health", "Cigna"],
    },
    timing: { opening_time: "08:00 AM", closing_time: "10:00 PM" },
    ratings: { avg_rating: 4.8, total_reviews: 3500 },
    graph: {
      success_rate: 95,
      hospital_rating: 94,
      doctors_rating: 98,
      average_rating: 96,
    },
    reviews: [
      {
        patient_name: "Sanjay G.",
        rating: 5,
        comment: "World leader in gastro care.",
      },
    ],
    image: "/uploads/hospitals/h29.jpeg",
  },

  {
    hospital_id: "H030",
    hospital_name: "Care Hospitals",
    hospital_type: "Private",
    description: "Excellence in cardiac and general healthcare.",
    location: {
      address: "Banjara Hills",
      city: "Hyderabad",
      state: "Telangana",
      country: "India",
      pincode: "500034",
    },
    contact: { phone: "9000100020", email: "care@carehospitals.com" },
    facilities: ["ICU", "Radiology", "Physiotherapy"],
    specializations: ["Cardiology", "Urology", "Gynecology"],
    hospital_stats: {
      total_doctors: 120,
      bed_capacity: 200,
      icu_beds: 30,
      operation_theatres: 6,
    },
    services: {
      emergency_24x7: true,
      ambulance_service: true,
      online_appointment: true,
      blood_bank_available: true,
      insurance_accepted: ["Niva Bupa", "Star Health"],
    },
    timing: { opening_time: "08:30 AM", closing_time: "08:30 PM" },
    ratings: { avg_rating: 4.4, total_reviews: 890 },
    graph: {
      success_rate: 90,
      hospital_rating: 85,
      doctors_rating: 93,
      average_rating: 89,
    },
    reviews: [
      {
        patient_name: "Lata M.",
        rating: 5,
        comment: "Very hygienic and fast service.",
      },
    ],
    image: "/uploads/hospitals/h30.jpeg",
  },
];

export default hospitals;
